Reenable the mutual exclusion check for --target and --library-mode. For photonics, just enable library mode under the covers since that target requires library mode.
Move some of the photonics code to using qvector and not qreg.

diff --git a/tools/nvqpp/nvq++.in b/tools/nvqpp/nvq++.in
--- a/tools/nvqpp/nvq++.in
+++ b/tools/nvqpp/nvq++.in
@@ -441,11 +441,8 @@ while [ $# -ne 0 ]; do
 		;;
 	--library-mode)
 		if [-n "${TARGET_CONFIG}"]; then
-			# Leave this commented out, since this combination is used
-			# in photonics.cpp
-			#echo "cannot use --library-mode with --target" >&2
-			#exit 2
-			true
+			echo "cannot use --library-mode with --target" >&2
+			exit 2
 		fi
 		LIBRARY_MODE=true
 		;;
