[core] Reimplement cudaq::run for C++.
For certain transport layers, there is a hard restriction that a kernel
cannot return a value. In CUDA-Q however, kernels have always been allowed
to return values. Moreover, kernels used with cudaq::run() are *required*
to return values.

Prior to these changes, the hard restrictions of the transport layer were
not being met. With these changes an entirely new kernel launch stack,
specifically for use with cudaq::run, will be autogenerated. This allows
for the kernel to exist as a CUDA-Q kernel and co-exist in a functionally
complete and semantically correct way with the host language, C++. At the
same time, the new second launch stack can exist and break the C++ semantics
so that new launch stack will unceremoniously drop return values on the
floor. This achieves the restriction imposed by the transport layer at the
expense of (mostly) duplicated code.

Additionally, instead of injecting output logging code into all entry
point kernels, the output logging code will be injected into the
cudaq::run kernels.

Add new op for output logging.

Fixes for Python.

Fix compiler errors.

Signed-off-by: Eric Schweitz <eschweitz@nvidia.com>

Remove check on struct size for now for targettests/execution/trivial_inliner.cpp test.

Update the tests.

Signed-off-by: Eric Schweitz <eschweitz@nvidia.com>

diff --git a/tools/nvqpp/nvq++.in b/tools/nvqpp/nvq++.in
--- a/tools/nvqpp/nvq++.in
+++ b/tools/nvqpp/nvq++.in
@@ -26,11 +26,11 @@ function error_exit {
 
 function run() {
 	if $ECHO; then
-		echo "$*"
+		echo "$@"
 	fi
-	$*
+	"$@"
 	if [ $? -ne 0 ]; then
-		echo "failed: \"$*\"" >&2
+		echo "failed: \"$@\"" >&2
 		exit 1
 	fi
 }
@@ -102,7 +102,7 @@ function f_option_handling {
 		ENABLE_LOWER_TO_CFG=true
 		;;
 	-fkernel-exec-kind=*)
-		KERNEL_EXECUTION_KIND="{codegen=${1#*=}}"
+		KERNEL_EXECUTION_KIND="codegen=${1#*=}"
 		;;
 	-fno-set-target-backend)
 		SET_TARGET_BACKEND=false
@@ -361,6 +361,7 @@ ENABLE_UNWIND_LOWERING=true
 ENABLE_DEVICE_CODE_LOADER=true
 ENABLE_KERNEL_EXECUTION=true
 KERNEL_EXECUTION_KIND=
+AUTO_GENERATE_RUN_OPTION=
 ENABLE_AGGRESSIVE_EARLY_INLINE=true
 ENABLE_LOWER_TO_CFG=true
 ENABLE_APPLY_SPECIALIZATION=true
@@ -712,6 +713,24 @@ if [[ "${PREPROCESSOR_DEFINES}" != *"CUDAQ_SIMULATION_SCALAR_"* ]]; then
 	fi
 fi
 
+# If ENABLE_CUDAQ_RUN is not set, then the user did not explicitly request it,
+# so we guard against using it with CUDAQ_QUANTUM_DEVICE. The user must still
+# set CUDAQ_ENABLE_QUANTUM_DEVICE_RUN=1 (env var) at runtime to enable support
+# at runtime. Note: this override is still required because no targets support
+# run yet.
+if [[ -z "${ENABLE_CUDAQ_RUN}" ]]; then
+	if [[ "${PREPROCESSOR_DEFINES}" != *"CUDAQ_QUANTUM_DEVICE"* ]]; then
+		CUDAQ_QUAKE_ARGS="${CUDAQ_QUAKE_ARGS} --cudaq-run=1"
+		AUTO_GENERATE_RUN_OPTION="generate-run-stack=1"
+	fi
+else
+	# we honor the user's explicit command-line request.
+	if ${ENABLE_CUDAQ_RUN}; then
+		CUDAQ_QUAKE_ARGS="${CUDAQ_QUAKE_ARGS} --cudaq-run=1"
+		AUTO_GENERATE_RUN_OPTION="generate-run-stack=1"
+	fi
+fi
+
 RUN_OPT=false
 OPT_PASSES=
 if ${ENABLE_VARIABLE_COALESCE}; then
@@ -732,7 +751,17 @@ if ${ENABLE_APPLY_SPECIALIZATION}; then
 fi
 if ${ENABLE_KERNEL_EXECUTION}; then
 	RUN_OPT=true
-	OPT_PASSES=$(add_pass_to_pipeline "${OPT_PASSES}" "kernel-execution${KERNEL_EXECUTION_KIND}")
+	KERNEL_EXECUTION_OPTIONS=
+	if [[ -n "${AUTO_GENERATE_RUN_OPTION}" ]]; then
+		if [[ -n "${KERNEL_EXECUTION_KIND}" ]]; then
+			KERNEL_EXECUTION_OPTIONS="{${KERNEL_EXECUTION_KIND} ${AUTO_GENERATE_RUN_OPTION}}"
+		else
+			KERNEL_EXECUTION_OPTIONS="{${AUTO_GENERATE_RUN_OPTION}}"
+		fi
+	elif [[ -n "${KERNEL_EXECUTION_KIND}" ]]; then
+		KERNEL_EXECUTION_OPTIONS="{${KERNEL_EXECUTION_KIND}}"
+	fi
+	OPT_PASSES=$(add_pass_to_pipeline "${OPT_PASSES}" "kernel-execution${KERNEL_EXECUTION_OPTIONS}")
 fi
 if ${ENABLE_AGGRESSIVE_EARLY_INLINE}; then
 	RUN_OPT=true
@@ -758,20 +787,6 @@ fi
 if ${ENABLE_LOWER_TO_CFG}; then
 	RUN_OPT=true
 	OPT_PASSES=$(add_pass_to_pipeline "${OPT_PASSES}" "expand-measurements,lower-to-cfg")
-fi
-# If ENABLE_CUDAQ_RUN is not set, then the user did not explicitly request it,
-# so we guard against using it with CUDAQ_QUANTUM_DEVICE. The user must still
-# set CUDAQ_ENABLE_QUANTUM_DEVICE_RUN=1 (env var) at runtime to enable support
-# at runtime. Note: this override is still required because no targets support
-# run yet.
-if [[ -z "${ENABLE_CUDAQ_RUN}" ]]; then
-	if [[ "${PREPROCESSOR_DEFINES}" != *"CUDAQ_QUANTUM_DEVICE"* ]]; then
-		CUDAQ_QUAKE_ARGS="${CUDAQ_QUAKE_ARGS} --cudaq-run=1"
-	fi
-else # we honor the user's explicit command-line request.
-	if ${ENABLE_CUDAQ_RUN}; then
-		CUDAQ_QUAKE_ARGS="${CUDAQ_QUAKE_ARGS} --cudaq-run=1"
-	fi
 fi
 if ${RUN_OPT}; then
 	OPT_PASSES=$(add_pass_to_pipeline "${OPT_PASSES}" "distributed-device-call,canonicalize,cse")
