Add more tests
Signed-off-by: Thien Nguyen <thiennguyen@nvidia.com>

diff --git a/unittests/backends/quantinuum/QuantinuumStartServerAndTest.sh.in b/unittests/backends/quantinuum/QuantinuumStartServerAndTest.sh.in
--- a/unittests/backends/quantinuum/QuantinuumStartServerAndTest.sh.in
+++ b/unittests/backends/quantinuum/QuantinuumStartServerAndTest.sh.in
@@ -32,7 +32,7 @@ while ! checkServerConnection; do
     exit 99
   fi
 done
-# Run the tests
+# Run the tests (gtest-based, not using nvq++)
 ./test_quantinuum
 # Did they fail? 
 testsPassed=$?
@@ -47,28 +47,64 @@ fi
 rm -f @CMAKE_BINARY_DIR@/FakeCppQuantinuum.config
 echo "key: key" >> @CMAKE_BINARY_DIR@/FakeCppQuantinuum.config
 echo "refresh: refresh" >> @CMAKE_BINARY_DIR@/FakeCppQuantinuum.config
-# Run the test for the QIR output
-@CMAKE_BINARY_DIR@/bin/nvq++ --target quantinuum --quantinuum-credentials @CMAKE_BINARY_DIR@/FakeCppQuantinuum.config --quantinuum-machine Helios-1SC --quantinuum-project mock --quantinuum-url http://localhost:62440 @CMAKE_SOURCE_DIR@/unittests/backends/quantinuum/test_run.cpp -o test_run.x
-./test_run.x
 
-if [ $testsPassed -ne 0 ]; then
-  echo "Test run failed with exit code $testsPassed"
-  # Clean up the config file
-  rm -f @CMAKE_BINARY_DIR@/FakeCppQuantinuum.config
-  kill -INT $pid
-  exit $testsPassed
+# Run all the nvq++ tests with mock server.
+echo "### nvq++ tests"
+set +e # Allow script to keep going through errors
+test_err_sum=0
+for filename in @CMAKE_SOURCE_DIR@/unittests/backends/quantinuum/test_*.cpp; do
+  echo "Testing $filename"
+  @CMAKE_BINARY_DIR@/bin/nvq++ --target quantinuum --quantinuum-credentials @CMAKE_BINARY_DIR@/FakeCppQuantinuum.config --quantinuum-machine Helios-1SC --quantinuum-project mock --quantinuum-url http://localhost:62440 $filename 
+  test_status=$?
+  if [ $test_status -eq 0 ]; then
+    ./a.out
+    test_status=$?
+    if [ $test_status -eq 0 ]; then
+      echo "Successfully ran test: $filename"
+    else
+      echo "Test failed (failed to execute): $filename" 
+      test_err_sum=$((test_err_sum+1))
+    fi
+  else
+    echo "Test failed (failed to compile): $filename" 
+    test_err_sum=$((test_err_sum+1))
+  fi
+done
+
+# Test separate compilation
+# Compile device code lib (with -fPIC -shared)
+@CMAKE_BINARY_DIR@/bin/nvq++ -fPIC -shared --target quantinuum --quantinuum-credentials @CMAKE_BINARY_DIR@/FakeCppQuantinuum.config --quantinuum-machine Helios-1SC --quantinuum-project mock --quantinuum-url http://localhost:62440 @CMAKE_SOURCE_DIR@/unittests/backends/quantinuum/run_separate_compilation/lib.cpp -o lib.so
+test_status=$?
+if [ $test_status -eq 0 ]; then
+  # Compile the app + linking to the lib
+  @CMAKE_BINARY_DIR@/bin/nvq++ --target quantinuum --quantinuum-credentials @CMAKE_BINARY_DIR@/FakeCppQuantinuum.config --quantinuum-machine Helios-1SC --quantinuum-project mock --quantinuum-url http://localhost:62440 @CMAKE_SOURCE_DIR@/unittests/backends/quantinuum/run_separate_compilation/app.cpp lib.so -o test_app.x
+  test_status=$?
+  if [ $test_status -eq 0 ]; then
+    ./test_app.x
+    test_status=$?
+    if [ $test_status -eq 0 ]; then
+      echo "Successfully ran app with device code library test"
+    else
+      echo "Test failed (failed to execute the app)" 
+      test_err_sum=$((test_err_sum+1))
+    fi
+  else
+    echo "Test failed (failed to compile the app)" 
+    test_err_sum=$((test_err_sum+1))
+  fi
+else
+  echo "Test failed (failed to compile the lib)" 
+  test_err_sum=$((test_err_sum+1))
 fi
 
-@CMAKE_BINARY_DIR@/bin/nvq++ --target quantinuum --quantinuum-credentials @CMAKE_BINARY_DIR@/FakeCppQuantinuum.config --quantinuum-machine Helios-1SC --quantinuum-project mock --quantinuum-url http://localhost:62440 @CMAKE_SOURCE_DIR@/unittests/backends/quantinuum/test_sample.cpp -o test_sample.x
-./test_sample.x
-
-# Did they fail?
-testsPassed=$?
 
 # Clean up the config file
 rm -f @CMAKE_BINARY_DIR@/FakeCppQuantinuum.config
-
-# kill the server
+# Stop the mock server
 kill -INT $pid
-# return success / failure
-exit $testsPassed
+
+set -e # Re-enable exit code error checking
+if [ ! $test_err_sum -eq 0 ]; then
+  echo "Error: ${test_err_sum} tests failed."
+  exit 1
+fi
