Adding workflow to push a release image to GHCR (#116)
This PR takes care of prerequisite 3 of #41.
Specifically, his PR
- enables the deployment of the devdeps.ext image to GHCR after pushes to main
- deploys a cuda-quantum image to GHCR that is build using the devdeps.ext image 
- updates the llvm-only build to use clang to bootstrap it (which is faster than gcc)
- enables image deployments upon pushes to main and release branches, while build cache updates are pushed after pr merges
- contains some clean up and improvements of the workflows.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,7 +9,7 @@ on:
       - 'main'
       - 'releases/*'
 
-name: CI
+name: CI # do not change name without updating workflow_run triggers
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
@@ -65,6 +65,7 @@ jobs:
     uses: ./.github/workflows/test_in_devenv.yml
     with:
       devdeps_cache: ${{ fromJson(needs.config.outputs.json).cache_key[format('{0}', matrix.toolchain)] }}
+      devdeps_archive: ${{ fromJson(needs.config.outputs.json).tar_archive[format('{0}', matrix.toolchain)] }}
       export_environment: ${{ github.event_name == 'workflow_dispatch' && inputs.export_environment }}
 
   build_and_test_llvm:
@@ -73,6 +74,7 @@ jobs:
     uses: ./.github/workflows/test_in_devenv.yml
     with:
       devdeps_cache: ${{ needs.setup_llvm.outputs.cache_key }}
+      devdeps_archive: ${{ needs.setup_llvm.outputs.tar_archive }}
       export_environment: ${{ github.event_name == 'workflow_dispatch' && inputs.export_environment }}
 
   docker_image:
@@ -81,3 +83,27 @@ jobs:
     uses: ./.github/workflows/build_packages.yml
     with:
       devdeps_cache: ${{ fromJson(needs.config.outputs.json).cache_key.gcc12 }}
+      devdeps_archive: ${{ fromJson(needs.config.outputs.json).tar_archive.gcc12 }}
+
+  clean_up:
+    name: Delete tar caches
+    runs-on: ubuntu-latest
+    needs: [config, setup_llvm, build_and_test, build_and_test_llvm, docker_image]
+    if: always() # need to clean up even if the workflow is cancelled or fails
+
+    steps:
+      - name: Save cache keys
+        id: workflow_inputs
+        run: |
+          set -e
+          key_matrix='${{ needs.config.outputs.json }}'
+          keys=`echo $key_matrix | jq '.cache_key | to_entries | .[].value' --raw-output`
+          keys+=" ${{ needs.setup_llvm.outputs.cache_key }}"
+          echo "$keys" >> cache_keys.txt
+
+      - uses: actions/upload-artifact@v3
+        with:
+          name: cache_keys_ci
+          path: cache_keys.txt
+          retention-days: 1
+          if-no-files-found: error
