cleaning up tar caches when creating local caches

diff --git a/.github/workflows/create_cache_command.yml b/.github/workflows/create_cache_command.yml
--- a/.github/workflows/create_cache_command.yml
+++ b/.github/workflows/create_cache_command.yml
@@ -77,11 +77,32 @@ jobs:
     name: Indicate completion
     runs-on: ubuntu-latest
     needs: [devdeps_caches, wheeldeps_caches]
+    # We need to clean up even if the workflow is cancelled or fails.
+    if: always()
+
     steps:
       - name: Add reaction to comment
-        if: inputs.comment_id
+        if: inputs.comment_id && success()
         uses: peter-evans/create-or-update-comment@v3
         with:
           comment-id: ${{ inputs.comment_id }}
           reactions-edit-mode: append
           reactions: hooray
+
+      - uses: cloudposse/github-action-matrix-outputs-read@0.1.1
+        id: read_json
+        with:
+          matrix-step-name: dev_environment
+
+      - run: |
+          set -e
+          key_matrix='${{ steps.read_json.outputs.result }}'
+          keys=`echo $key_matrix | jq '.cache_key | to_entries | .[].value' --raw-output`
+          keys+=" ${{ needs.wheeldeps_caches.outputs.cache_key }}"
+          gh extension install actions/gh-actions-cache
+          for key in $keys; do
+            echo "Deleting cache $key"
+            gh actions-cache delete $key -R ${{ github.repository }} --confirm
+          done
+        env:
+          GH_TOKEN: ${{ github.token }}
