Updating badges and various fixes (#352)

diff --git a/.github/workflows/docker_images.yml b/.github/workflows/docker_images.yml
--- a/.github/workflows/docker_images.yml
+++ b/.github/workflows/docker_images.yml
@@ -46,7 +46,7 @@ jobs:
 
     environment:
       name: ${{ inputs.environment || 'default' }}
-      url: ${{ vars.deployment_url }}
+      url: ${{ vars.deployment_url || github.repository }}
   
     steps:
       - name: Checkout repository
@@ -64,7 +64,8 @@ jobs:
         id: build_info
         run: |
           repo_owner=${{ github.repository_owner }}
-          image_name=${{ vars.registry || 'ghcr.io' }}/${repo_owner,,}/open-mpi
+          registry=${{ vars.registry || 'localhost:5000' }}
+          image_name=$registry/${repo_owner,,}/open-mpi
           echo "image_name=$image_name" >> $GITHUB_OUTPUT
 
           docker pull ${{ inputs.ompidev_image }} # to get the tag
@@ -133,7 +134,7 @@ jobs:
 
     environment:
       name: ${{ inputs.environment || 'default' }}
-      url: ${{ vars.deployment_url }}
+      url: ${{ vars.deployment_url || github.repository }}
 
     # Needed for making local images available to the docker/build-push-action.
     # See also https://stackoverflow.com/a/63927832.
@@ -182,7 +183,8 @@ jobs:
           fi
 
           repo_owner=${{ github.repository_owner }}
-          image_name=${{ vars.registry || 'ghcr.io' }}/${repo_owner,,}/cuda-quantum-dev
+          registry=${{ vars.registry || 'localhost:5000' }}
+          image_name=$registry/${repo_owner,,}/cuda-quantum-dev
           image_tag=`docker inspect $base_image --format='{{json .Config.Labels}}' | jq -r '."org.opencontainers.image.version"'`
           docker image rm $base_image
           docker image prune --force
@@ -253,7 +255,7 @@ jobs:
 
     environment:
       name: ${{ inputs.environment || 'default' }}
-      url: ${{ vars.deployment_url }}
+      url: ${{ vars.deployment_url || github.repository }}
 
     # Needed for making local images available to the docker/build-push-action.
     # See also https://stackoverflow.com/a/63927832.
@@ -325,7 +327,8 @@ jobs:
 
           docker image prune --force
           repo_owner=${{ github.repository_owner }}
-          image_name=${{ vars.registry || 'ghcr.io' }}/${repo_owner,,}/cuda-quantum
+          registry=${{ vars.registry || 'localhost:5000' }}
+          image_name=$registry/${repo_owner,,}/cuda-quantum
           if ${{ github.event.pull_request.number != '' }}; then
             image_tag=pr-${{ github.event.pull_request.number }}
           elif ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}; then
@@ -541,6 +544,9 @@ jobs:
           docker cp scripts/validate_container.sh cuda-quantum:"/home/cudaq/validate_container.sh"
           docker exec -e TERM=xterm cuda-quantum bash validate_container.sh > /tmp/validation.out
           docker stop cuda-quantum
+          if ${{ inputs.ompidev_image != '' }} && [ "$(cat /tmp/validation.out | grep '^nvidia$')" != "nvidia" ]; then
+            echo "Missing installation for nvidia backend." && exit 1
+          fi
 
       - name: Create job summary
         if: always() && !cancelled()
@@ -585,9 +591,9 @@ jobs:
           info_file="deployments/staging/cuda-quantum-dev/$file_id"
           echo "info_file=$info_file" >> $GITHUB_OUTPUT
 
-          mkdir -p "$(dirname "$info_file")"
-          echo "release-id: $release_id" > "$info_file"
-          echo "publish: ${{ inputs.create_release }}" > "$info_file"
+          mkdir -p "$(dirname "$info_file")" && rm -rf "$info_file"
+          echo "release-id: $release_id" >> "$info_file"
+          echo "publish: ${{ inputs.create_release }}" >> "$info_file"
           echo "source-sha: ${{ github.sha }}" >> "$info_file"
           echo "cuda-quantum-dev-image: $cudaqdev_hash"  >> "$info_file"
           echo "cuda-quantum-image: $cudaq_hash" >> "$info_file"
