Update docker_images.yml

diff --git a/.github/workflows/docker_images.yml b/.github/workflows/docker_images.yml
--- a/.github/workflows/docker_images.yml
+++ b/.github/workflows/docker_images.yml
@@ -547,27 +547,29 @@ jobs:
           path: ${{ steps.prereqs.outputs.tar_archive }}
           key: ${{ steps.prereqs.outputs.tar_cache }}
 
-      - name: Sign image
-        if: inputs.environment
+      - name: Sign image with GitHub OIDC Token
+        if: inputs.environment && steps.prereqs.outputs.ngc_registry == ''
         env:
           DIGEST: ${{ steps.cudaq_build.outputs.digest }}
+          TAGS: ${{ steps.cudaq_metadata.outputs.tags }}
+        run: cosign sign --yes --recursive "${TAGS}@${DIGEST}"
+
+      - name: Sign image with NGC CLI
+        if: inputs.environment && steps.prereqs.outputs.ngc_registry
+        env:
           TAGS: ${{ steps.cudaq_metadata.outputs.tags }}
           NGC_CLI_API_KEY: ${{ secrets.NGC_CREDENTIALS }}
           NGC_CLI_ORG: ${{ github.repository_owner }}
           NGC_CLI_TEAM: 'nightly'
         run: |
-          if ${{ steps.prereqs.outputs.ngc_registry != '' }}; then
-            wget -O ngccli_linux.zip --content-disposition \
-              https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/3.28.0/files/ngccli_linux.zip
-            if [ -z "$(sha256sum ngccli_linux.zip | grep -o '74f469a2082e90a4561f09eb0d483b67044e91be727066122253436c140a7b54 ')" ]; then
-              echo "::error::NGC CLI was corrupted during download." && exit 1
-            fi
-            unzip ngccli_linux.zip && chmod u+x ngc-cli/ngc
-            echo "Signing ${TAGS}"
-            ngc-cli/ngc registry image publish --source ${TAGS} ${TAGS} --sign
-          else
-            cosign sign --yes --recursive "${TAGS}@${DIGEST}"
+          wget -O ngccli_linux.zip --content-disposition \
+            https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/3.28.0/files/ngccli_linux.zip
+          if [ -z "$(sha256sum ngccli_linux.zip | grep -o '74f469a2082e90a4561f09eb0d483b67044e91be727066122253436c140a7b54 ')" ]; then
+            echo "::error::NGC CLI was corrupted during download." && exit 1
           fi
+          unzip ngccli_linux.zip && chmod u+x ngc-cli/ngc
+          echo "Signing ${TAGS}"
+          ngc-cli/ngc registry image publish --source ${TAGS} ${TAGS} --sign
 
       # If the cuda-quantum image is initially pushed to ngc we recreate it
       # and push it to the registry defined in the deployment environment
