running examples during deployment

diff --git a/.github/workflows/docker_images.yml b/.github/workflows/docker_images.yml
--- a/.github/workflows/docker_images.yml
+++ b/.github/workflows/docker_images.yml
@@ -704,9 +704,13 @@ jobs:
 
           docker run --rm -dit --name cuda-quantum $cudaq_image
           docker cp scripts/validate_container.sh cuda-quantum:"/home/cudaq/validate_container.sh"
-          docker exec cuda-quantum bash validate_container.sh > /tmp/validation.out
+          (docker exec cuda-quantum bash validate_container.sh > /tmp/validation.out) && passed=true || passed=false
           docker stop cuda-quantum
-          if ${{ inputs.ompidev_image != '' }} && [ "$(cat /tmp/validation.out | grep '^nvidia$')" != "nvidia" ]; then
+
+          if ! $passed; then 
+            echo "::error::Validation failed; see job summary for more details."
+            exit 1
+          elif ${{ inputs.ompidev_image != '' }} && [ "$(cat /tmp/validation.out | grep '^nvidia$')" != "nvidia" ]; then
             echo "Missing installation for nvidia backend." && exit 1
           fi
 
diff --git a/.github/workflows/prebuilt_binaries.yml b/.github/workflows/prebuilt_binaries.yml
--- a/.github/workflows/prebuilt_binaries.yml
+++ b/.github/workflows/prebuilt_binaries.yml
@@ -120,5 +120,57 @@ jobs:
           (docker exec cuda-quantum bash -c nvq++) && installed=true || installed=false
           docker stop cuda-quantum
 
-          if ! $installed; then echo "Failed to install CUDA Quantum." >> /tmp/validation.out
-          else echo "Successfully installed CUDA Quantum." >> /tmp/validation.out; fi
+          if ! $installed; then echo "Failed to install CUDA Quantum." && exit 1
+          else echo "Successfully installed CUDA Quantum."; fi
+
+      - name: MPI validation
+        uses: ./.github/actions/run-in-docker
+        with:
+          image: validation:local
+          shell: bash
+          run: |
+            set +e # Allow script to keep going through errors
+            for ex in `find examples/other/distributed/ -name '*.cpp'`; do
+              nvq++ -DCUDAQ_ENABLE_MPI_EXAMPLE=1 $ex
+              status=$?
+              if [ $status -eq 0 ]; then
+                mpiexec --allow-run-as-root -np 4 ./a.out
+                status=$?
+                if [ $status -eq 0 ]; then
+                  echo "Successfully ran $filename."
+                else
+                  echo "Failed to execute $filename."
+                  status_sum=$((status_sum+1))
+                fi
+              else
+                echo "Compilation failed for $filename."
+                status_sum=$((status_sum+1))
+              fi
+            done
+            set -e # Re-enable exit code error checking
+            if [ ! $status_sum -eq 0 ]; then
+              echo "::error::$status_sum examples failed; see the log for more detail."
+              exit $status_sum
+            fi
+
+      - name: Sanity checks
+        run: |
+          docker run --rm -dit --name cuda-quantum validation:local
+          (docker exec cuda-quantum bash validate.sh > /tmp/validation.out) && passed=true || passed=false
+          docker stop cuda-quantum
+
+          if ! $passed; then 
+            echo "::error::Validation failed; see job summary for more details."
+            exit 1
+          fi
+
+      - name: Create job summary
+        if: always() && !cancelled()
+        run: |
+          if [ -f /tmp/validation.out ]; then
+            echo "## Validation" >> $GITHUB_STEP_SUMMARY
+            echo "The validation of the CUDA Quantum installation produced the following output:" >> $GITHUB_STEP_SUMMARY
+            echo '```text' >> $GITHUB_STEP_SUMMARY
+            cat /tmp/validation.out >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+          fi
