[CI] [testing] Create the required authentication token in the shell environment (#2875)
A valid set of credentials (PASQAL_AUTH_TOKEN, PASQAL_PROJECT_ID) are required to run the Pasqal examples. These can be generated from the Python module - `pasqal_cloud`.

Signed-off-by: Pradnya Khalate <pkhalate@nvidia.com>
Signed-off-by: Anna Gringauze <agringauze@nvidia.com>

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -705,7 +705,29 @@ jobs:
           export PASQAL_PROJECT_ID='${{ secrets.PASQAL_PROJECT_ID }}'
           export PASQAL_MACHINE_TARGET="EMU_FREE" # Speedup queuing time
           set +e # Allow script to keep going through errors
+          echo "### Generating Pasqal auth token" >> $GITHUB_STEP_SUMMARY
+          PASQAL_AUTH_TOKEN=$(python3 -c "import pasqal_cloud; import os; import sys; sdk = SDK(username=os.environ.get("PASQAL_USERNAME"), password=os.environ.get("PASQAL_PASSWORD")); sys.stdout.write(str(sdk.user_token()))")
+          export PASQAL_AUTH_TOKEN
           test_err_sum=0
+          cpp_tests="docs/sphinx/targets/cpp/pasqal.cpp"
+          for filename in $cpp_tests; do
+            [ -e "$filename" ] || echo "::error::Couldn't find file ($filename)"
+            nvq++ --target pasqal  --pasqal-machine $PASQAL_MACHINE_TARGET  $filename
+            test_status=$?
+            if [ $test_status -eq 0 ]; then
+              ./a.out 1> /dev/null
+              test_status=$?
+              if [ $test_status -eq 0 ]; then
+                echo ":white_check_mark: Successfully ran test: $filename" >> $GITHUB_STEP_SUMMARY
+              else
+                echo ":x: Test failed (failed to execute): $filename" >> $GITHUB_STEP_SUMMARY
+                test_err_sum=$((test_err_sum+1))
+              fi
+            else
+              echo ":x: Test failed (failed to compile): $filename" >> $GITHUB_STEP_SUMMARY
+              test_err_sum=$((test_err_sum+1))
+            fi
+          done
           python_tests="docs/sphinx/targets/python/pasqal.py"
           for filename in $python_tests; do
             [ -e "$filename" ] || echo "::error::Couldn't find file ($filename)"
