Update the `quantinuum` target to use Nexus service (#3286)
* Create a skeleton for Nexus-based Quantinuum Server Helper.
* Retaining old one with the suffix '_legacy' for temporary testing purposes.

Signed-off-by: Pradnya Khalate <pkhalate@nvidia.com>

* Code to support basic authentication and result parsing (#3231)
* [WIP] work on nexus rest API
* Some place holder implementation
* Simplified the implementation
* Update according to test
* Clang-format
* Support bit register result parsing (#3245)
* Also checking for the availability of 'result_id' to determine job completion (#3249)

Signed-off-by: Thien Nguyen <thiennguyen@nvidia.com>

* Nexus job creation (#3237)
* Create job
* Use two separate POST APIs for job creation.
* Adding cookies to the server payload
* Append timestamp to job name
* Accept project ID from user
* Mock server update
* Skip project requirement in emulation mode
* Test clean up
* Use the new `getCookies` method instead of changing `ServerJobPayload`
* Fix the mock server's result endpoint
* Clean up the legacy server (#3259)
* Clean up mock server

Signed-off-by: Pradnya Khalate <pkhalate@nvidia.com>

* Populate sequential data for all registers (#3260)
* Fix mock server
* Code review: adding back a validation assertion

Signed-off-by: Thien Nguyen <thiennguyen@nvidia.com>

* [docs] Update Nexus documentation (#3278)
* Update the login method
* Update examples to include Nexus project argument
* User documentation to get to Nexus
* Add Python test to integration
* Spellcheck
* Addressing review comments

Signed-off-by: Pradnya Khalate <pkhalate@nvidia.com>

---------

Signed-off-by: Pradnya Khalate <pkhalate@nvidia.com>
Signed-off-by: Thien Nguyen <thiennguyen@nvidia.com>
Co-authored by: Thien Nguyen <thiennguyen@nvidia.com>
Co-authored-by: Thien Nguyen <58006629+1tnguyen@users.noreply.github.com>
Signed-off-by: ikkoham <ikkoham@users.noreply.github.com>

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -391,11 +391,10 @@ jobs:
       - name: Setup quantinum account
         if: (success() || failure()) && (github.event_name == 'schedule' || inputs.target == 'nightly' || inputs.target == 'quantinuum')
         run: |
-          curl -X POST -H "Content Type: application/json" -d '{ "email":"${{ secrets.BACKEND_LOGIN_EMAIL }}","password":"${{ secrets.QUANTINUUM_PASSWORD }}" }' https://qapi.quantinuum.com/v1/login > credentials.json
-          id_token=`cat credentials.json | jq -r '."id-token"'`
-          refresh_token=`cat credentials.json | jq -r '."refresh-token"'`
-          echo "key: $id_token" > ~/.quantinuum_config
-          echo "refresh: $refresh_token" >> ~/.quantinuum_config
+          echo "### Setup Quantinuum account" >> $GITHUB_STEP_SUMMARY
+          curl -c ~/.quantinuum_cookies.txt -X POST https://nexus.quantinuum.com/auth/login -H "Content-Type: application/json" -d '{ "email":"${{ secrets.BACKEND_LOGIN_EMAIL }}","password":"${{ secrets.QUANTINUUM_NEXUS_PASSWORD }}" }' >/dev/null
+          awk '$6 == "myqos_oat" {refresh=$7} $6 == "myqos_id" {key=$7} END {print "key: " key "\nrefresh: " refresh}' ~/.quantinuum_cookies.txt > ~/.quantinuum_config
+          rm ~/.quantinuum_cookies.txt
 
       - name: QIR syntax check (Quantinuum)
         if: (success() || failure()) && (github.event_name == 'schedule' || inputs.target == 'nightly')
@@ -408,7 +407,7 @@ jobs:
             case $filename in
               targettests/quantinuum/*)
                 [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"
-                nvq++ -v $filename -DSYNTAX_CHECK --target quantinuum --quantinuum-machine H1-1SC
+                nvq++ -v $filename -DSYNTAX_CHECK --target quantinuum --quantinuum-machine H1-1SC --quantinuum-project ${{ secrets.QUANTINUUM_NEXUS_PROJECT_ID }}
                 test_status=$?
                 if [ $test_status -eq 0 ]; then
                   ./a.out
@@ -425,6 +424,18 @@ jobs:
                 fi
               ;;
             esac
+          done
+          python_tests="docs/sphinx/targets/python/quantinuum.py"
+          for filename in $python_tests; do
+            [ -e "$filename" ] || echo "::error::Couldn't find file ($filename)"
+            QUANTINUUM_NEXUS_PROJECT=${{ secrets.QUANTINUUM_NEXUS_PROJECT_ID }} python3 $filename 1> /dev/null
+            test_status=$?
+            if [ $test_status -eq 0 ]; then
+              echo ":white_check_mark: Successfully ran test: $filename" >> $GITHUB_STEP_SUMMARY
+            else
+              echo ":x: Test failed (failed to execute): $filename" >> $GITHUB_STEP_SUMMARY
+              test_err_sum=$((test_err_sum+1))
+            fi
           done
           set -e # Re-enable exit code error checking
           if [ ! $test_err_sum -eq 0 ]; then
