* Run Python test(s) as part of the integration test suite.

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -421,9 +421,9 @@ jobs:
           export ORCA_ACCESS_URL='${{ secrets.ORCA_ACCESS_URL }}'
           set +e # Allow script to keep going through errors
           test_err_sum=0
-          testlist="docs/sphinx/examples/cpp/providers/orca.cpp"
-          for filename in $testlist; do
-            [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"           
+          cpp_tests="docs/sphinx/examples/cpp/providers/orca.cpp"
+          for filename in $cpp_tests; do
+            [ -e "$filename" ] || echo "::error::Couldn't find file ($filename)"
             nvq++ --target orca --orca-url $ORCA_ACCESS_URL $filename
             test_status=$?
             if [ $test_status -eq 0 ]; then
@@ -438,14 +438,27 @@ jobs:
             else
               echo ":x: Test failed (failed to compile): $filename" >> $GITHUB_STEP_SUMMARY
               test_err_sum=$((test_err_sum+1))
-            fi              
+            fi
           done
+          python_tests="docs/sphinx/examples/python/providers/orca.py"
+          for filename in $python_tests; do
+            [ -e "$filename" ] || echo "::error::Couldn't find file ($filename)"
+            python3 $filename 1> /dev/null
+            test_status=$?
+            if [ $test_status -eq 0 ]; then
+              echo ":white_check_mark: Successfully ran test: $filename" >> $GITHUB_STEP_SUMMARY
+            else
+              echo ":x: Test failed (failed to execute): $filename" >> $GITHUB_STEP_SUMMARY
+              test_err_sum=$((test_err_sum+1))
+            fi
+          done
+          set -e # Re-enable exit code error checking
           if [ ! $test_err_sum -eq 0 ]; then
             echo "::error::${test_err_sum} tests failed. See step summary for a list of failures"
             exit 1
           fi
         shell: bash
-      
+
       - name: Submit to ${{ inputs.target }}
         # The full set of tests used by this step is currently only supported on
         # Quantinuum.  The other supported tests are tested by the step above.
