Add adaptive profile integration test

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -114,22 +114,27 @@ jobs:
           set +e # Allow script to keep going through errors
           test_err_sum=0
           for filename in ${{ steps.gettests.outputs.testlist }}; do
-            [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"
-            nvq++ -v $filename --target ionq
-            test_status=$?
-            if [ $test_status -eq 0 ]; then
-              ./a.out
-              test_status=$?
-              if [ $test_status -eq 0 ]; then
-                echo ":white_check_mark: Successfully ran test: $filename" >> $GITHUB_STEP_SUMMARY
-              else
-                echo ":x: Test failed (failed to execute): $filename" >> $GITHUB_STEP_SUMMARY
-                test_err_sum=$((test_err_sum+1))
-              fi
-            else
-              echo ":x: Test failed (failed to compile): $filename" >> $GITHUB_STEP_SUMMARY
-              test_err_sum=$((test_err_sum+1))
-            fi
+            case $filename in
+              test/NVQPP/integration/testConditionalSample.cpp)
+                echo ":white_flag: Test skipped because this target doesn't support the Adaptive Profile: $filename" >> $GITHUB_STEP_SUMMARY ;;
+              *)
+                [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"
+                nvq++ -v $filename --target ionq
+                test_status=$?
+                if [ $test_status -eq 0 ]; then
+                  ./a.out
+                  test_status=$?
+                  if [ $test_status -eq 0 ]; then
+                    echo ":white_check_mark: Successfully ran test: $filename" >> $GITHUB_STEP_SUMMARY
+                  else
+                    echo ":x: Test failed (failed to execute): $filename" >> $GITHUB_STEP_SUMMARY
+                    test_err_sum=$((test_err_sum+1))
+                  fi
+                else
+                  echo ":x: Test failed (failed to compile): $filename" >> $GITHUB_STEP_SUMMARY
+                  test_err_sum=$((test_err_sum+1))
+                fi
+            esac
           done
           set -e # Re-enable exit code error checking
           if [ ! $test_err_sum -eq 0 ]; then
@@ -170,6 +175,8 @@ jobs:
             [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"
             # Only the following tests are currently supported on IQM
             case $filename in
+              test/NVQPP/integration/testConditionalSample.cpp)
+                echo ":white_flag: Test skipped because this target doesn't support the Adaptive Profile: $filename" >> $GITHUB_STEP_SUMMARY ;;
               test/NVQPP/integration/bug_qubit.cpp|\
               test/NVQPP/integration/callable_kernel_arg.cpp|\
               test/NVQPP/integration/if_jit.cpp|\
@@ -233,6 +240,8 @@ jobs:
             [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"
             # Only the following tests are currently supported on OQC
             case $filename in
+              test/NVQPP/integration/testConditionalSample.cpp)
+                echo ":white_flag: Test skipped because this target doesn't support the Adaptive Profile: $filename" >> $GITHUB_STEP_SUMMARY ;;
               test/NVQPP/integration/bug_qubit.cpp|\
               test/NVQPP/integration/callable_kernel_arg.cpp|\
               test/NVQPP/integration/if_jit.cpp|\
@@ -268,8 +277,11 @@ jobs:
         shell: bash
 
       - name: Submit to ${{ inputs.target }}
-        # The full set of tests used by this step is currently only supported on Quantinuum.
-        # The IonQ-supported tests are tested by the step above.
+        # The full set of tests used by this step is currently only supported on
+        # Quantinuum.  The other supported tests are tested by the step above.
+        # The main point of this special step is to run with a special
+        # target_machine. It also doesn't use -DSYNTAX_CHECK, so you probably
+        # don't want to run this on a simple Syntax Check machine.
         if: inputs.target == 'quantinuum' && github.event_name == 'workflow_dispatch'
         run: |
           if ${{inputs.target == 'ionq'}}; then
