Add cleanup

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -32,6 +32,7 @@ jobs:
     name: Build NVCF deployment image
     runs-on: ubuntu-latest
     environment: backend-validation
+    if: (inputs.target == 'nvcf' || github.event_name == 'schedule' || inputs.target == 'nightly')
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -69,6 +70,7 @@ jobs:
     name: Deploy NVCF function
     runs-on: ubuntu-latest
     needs: build_nvcf_image
+    if: (inputs.target == 'nvcf' || github.event_name == 'schedule' || inputs.target == 'nightly')
     environment: backend-validation
     steps:
       - name: Checkout repository
@@ -118,6 +120,7 @@ jobs:
   integration_test:
     name: Integration test
     runs-on: ubuntu-latest
+    needs: [build_nvcf_image, deploy_nvcf_test_function]
     environment: backend-validation
     container:
       # TODO: switch back to `cuda-quantum:latest` once the publishing image is ready
@@ -487,3 +490,33 @@ jobs:
             exit 1
           fi
         shell: bash
+
+  cleanup_nvcf_resources:
+    name: Cleanup NVCF resources
+    runs-on: ubuntu-latest
+    needs: [build_nvcf_image, deploy_nvcf_test_function, integration_test]
+    if: (success() || failure()) && (inputs.target == 'nvcf' || github.event_name == 'schedule' || inputs.target == 'nightly')
+    environment: backend-validation
+    steps:
+      - name: Install NGC CLI
+        run: |
+          sudo apt-get update && sudo apt-get install -y --no-install-recommends wget
+          wget -O ngccli_linux.zip --content-disposition \
+            https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/3.38.0/files/ngccli_linux.zip
+          if [ -z "$(sha256sum ngccli_linux.zip | grep -o '427c67684d792b673b63882a6d0cbb8777815095c0f2f31559c1570a91187388 ')" ]; then
+            echo "::error::NGC CLI was corrupted during download." && exit 1
+          fi
+          unzip ngccli_linux.zip && chmod u+x ngc-cli/ngc
+
+      - name: Cleanup
+        env:
+          NGC_CLI_API_KEY: ${{ secrets.NGC_NVCF_CREDENTIALS }}
+          NGC_CLI_ORG: ${{ secrets.NGC_NVCF_ORG }}
+          NGC_CLI_TEAM: cuda-quantum
+        run: |
+          # Remove deployment (make it inactive)
+          ngc-cli/ngc cloud-function function deploy remove ${{ secrets.NVCF_FUNCTION_ID }}:${{ needs.deploy_nvcf_test_function.outputs.nvcf_function_version_id }}
+          # Remove the function version
+          ngc-cli/ngc cloud-function function remove ${{ secrets.NVCF_FUNCTION_ID }}:${{ needs.deploy_nvcf_test_function.outputs.nvcf_function_version_id }}
+          # Remove the docker image
+          ngc-cli/ngc registry image remove -y nvcr.io/${{ secrets.NGC_NVCF_ORG }}/cuda-quantum/cuda-quantum:nightly
