Add deploy step

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -100,6 +100,19 @@ jobs:
             ${{ secrets.NVCF_FUNCTION_ID }})
           version_id=$(echo "$create_function_result" | grep 'Version: \S*' |  head -1 | cut -d ':' -f 2)
           echo "Create version Id: $version_id"
+          echo "nvcf_function_version_id=$version_id" >> $GITHUB_OUTPUT
+          # Deploy it
+          ngc-cli/ngc cloud-function function deploy create --deployment-specification ${{ secrets.NGC_NVCF_DEPLOYMENT_SPEC }} ${{ secrets.NVCF_FUNCTION_ID }}:$version_id
+          function_status=DEPLOYING
+          while [ "$function_status" =  "DEPLOYING" ];
+            do echo "Waiting for deploying NVCF function version $version_id ..." && sleep 300; 
+            function_info=$(ngc-cli/ngc cloud-function function info ${{ secrets.NVCF_FUNCTION_ID }}:$version_id)
+            function_status=$(echo "$function_info" | grep 'Status: \S*' |  head -1 | cut -d ':' -f 2)
+          done
+          if [ "$function_status" !=  "ACTIVE" ]
+            echo "::error:: Failed to deploy NVCF Test Function"
+            exit 1
+          fi
 
   integration_test:
     name: Integration test
