Add support for specifying a single test

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -4,10 +4,6 @@ name: Nightly integration tests
 on:
   workflow_dispatch:
     inputs:
-      syntax_check:
-        type: boolean
-        required: true
-        description: 'Run syntax checker (Quantinuum).'
       target:
         description: 'Target (choose nightly to run like nightly tests)'
         required: true
@@ -19,6 +15,10 @@ on:
           - iqm
           - oqc
           - quantinuum
+      single_test_name:
+        type: string
+        required: false
+        description: 'Single test (e.g., test/NVQPP/integration/load_value.cpp). Runs default tests if left blank'
       target_machine:
         type: string
         required: false
@@ -47,8 +47,24 @@ jobs:
           ref: ${{ steps.commit-sha.outputs.sha }}
           fetch-depth: 1
 
+      - name: Get tests
+        id: gettests
+        run: |
+          if [ -n "${{ inputs.single_test_name }}" ]; then
+            if [ -e ${{ inputs.single_test_name }} ]; then
+              echo "testlist=${{ inputs.single_test_name }}" >> $GITHUB_OUTPUT
+            else
+              # User's request test does not exit
+              echo "::error::File ${{ inputs.single_test_name}} not found"
+              exit 1
+            fi
+          else
+            filelist="test/NVQPP/integration/*.cpp"
+            echo "testlist=$filelist" >> $GITHUB_OUTPUT
+          fi
+
       - name: Setup quantinum account
-        if: github.event_name == 'schedule' || inputs.target == 'nightly' || inputs.syntax_check || inputs.target == 'quantinuum'
+        if: github.event_name == 'schedule' || inputs.target == 'nightly' || inputs.target == 'quantinuum'
         run: |
           curl -X POST -H "Content Type: application/json" -d '{ "email":"${{ secrets.BACKEND_LOGIN_EMAIL }}","password":"${{ secrets.QUANTINUUM_PASSWORD }}" }' https://qapi.quantinuum.com/v1/login > credentials.json
           id_token=`cat credentials.json | jq -r '."id-token"'`
@@ -57,13 +73,13 @@ jobs:
           echo "refresh: $refresh_token" >> ~/.quantinuum_config
 
       - name: QIR syntax check (Quantinuum)
-        if: inputs.syntax_check || github.event_name == 'schedule' || inputs.target == 'nightly'
+        if: github.event_name == 'schedule' || inputs.target == 'nightly'
         run: |
           echo "### QIR syntax check (Quantinuum)" >> $GITHUB_STEP_SUMMARY
           export CUDAQ_LOG_LEVEL="info"
           set +e # Allow script to keep going through errors
           test_err_sum=0
-          for filename in test/NVQPP/integration/*.cpp; do
+          for filename in ${{ steps.gettests.outputs.testlist }}; do
             [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"
             nvq++ -v $filename -DSYNTAX_CHECK --target quantinuum --quantinuum-machine H1-1SC
             test_status=$?
@@ -97,7 +113,7 @@ jobs:
           export CUDAQ_LOG_LEVEL="info"
           set +e # Allow script to keep going through errors
           test_err_sum=0
-          for filename in test/NVQPP/integration/*.cpp; do
+          for filename in ${{ steps.gettests.outputs.testlist }}; do
             [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"
             nvq++ -v $filename --target ionq
             test_status=$?
@@ -150,7 +166,7 @@ jobs:
           export CUDAQ_LOG_LEVEL="info"
           set +e # Allow script to keep going through errors
           test_err_sum=0
-          for filename in test/NVQPP/integration/*.cpp; do
+          for filename in ${{ steps.gettests.outputs.testlist }}; do
             [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"
             # Only the following tests are currently supported on IQM
             case $filename in
@@ -213,7 +229,7 @@ jobs:
           export OQC_PASSWORD="${{ secrets.OQC_PASSWORD }}"
           set +e # Allow script to keep going through errors
           test_err_sum=0
-          for filename in test/NVQPP/integration/*.cpp; do
+          for filename in ${{ steps.gettests.outputs.testlist }}; do
             [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"
             # Only the following tests are currently supported on OQC
             case $filename in
@@ -258,12 +274,10 @@ jobs:
         run: |
           if ${{inputs.target == 'ionq'}}; then
             export IONQ_API_KEY="${{ secrets.IONQ_API_KEY }}"
-            # TODO: remove this flag once https://github.com/NVIDIA/cuda-quantum/issues/512 is addressed.
-            export IONQ_FLAG="-DIONQ_TARGET"
           fi
-          for filename in test/NVQPP/integration/*.cpp; do
+          for filename in ${{ steps.gettests.outputs.testlist }}; do
             [ -e "$filename" ] || echo "::error::Couldn't find files ($filename)"
-            nvq++ -v $IONQ_FLAG $filename --target ${{ inputs.target }} --${{ inputs.target }}-machine ${{ inputs.target_machine }}
+            nvq++ -v $filename --target ${{ inputs.target }} --${{ inputs.target }}-machine ${{ inputs.target_machine }}
             CUDAQ_LOG_LEVEL=info ./a.out
           done
         shell: bash
