Add wheel validation

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -33,12 +33,16 @@ on:
         type: string
         required: false
         default: 'nvcr.io/nvidia/nightly/cuda-quantum:latest'
-        description: 'CUDA Quantum image to run the tests in. Default to the latest CUDA Quantum nightly image.'
+        description: 'CUDA Quantum image to run the tests in. Default to the latest CUDA Quantum nightly image'
       cudaq_nvcf_deploy_image:
         type: string
         required: false
         default: 'nvcr.io/nvidia/nightly/cuda-quantum:latest'
-        description: 'CUDA Quantum image to use for NVCF deployment. Default to the latest CUDA Quantum nightly image.'
+        description: 'CUDA Quantum image to use for NVCF deployment. Default to the latest CUDA Quantum nightly image'
+      workflow_id:
+        type: string
+        required: false
+        description: 'Workflow Id to retrieve the Python wheel for testing. Default to the latest Publishing workflow of the main branch if left blank'
 
   schedule:
     - cron: 0 3 * * *
@@ -134,7 +138,7 @@ jobs:
           fi
 
   integration_test:
-    name: Integration test
+    name: Integration test using Docker
     runs-on: ubuntu-latest
     needs: [build_nvcf_image, deploy_nvcf_test_function]
     environment: backend-validation
@@ -497,10 +501,62 @@ jobs:
           fi
         shell: bash
 
+  wheel_integration_test:
+    name: Integration test using Python wheels
+    runs-on: ubuntu-latest
+    needs: [build_nvcf_image, deploy_nvcf_test_function]
+    environment: backend-validation
+    if: (success() || failure()) && (inputs.target == 'nvcf' || github.event_name == 'schedule' || inputs.target == 'nightly')
+
+    steps:
+      - name: Install wheel
+        run: |
+          workflow_id= ${{ inputs.workflow_id }} 
+          if [ -z "${workflow_id}" ]; then
+            workflow_id=$(gh run list --branch main --workflow Publishing --status completed --event workflow_dispatch --limit 1 --json databaseId | jq '.[0].databaseId')
+          fi
+          echo "Using artifacts from workflow id $workflow_id"
+          gh run download $workflow_id
+          apt-get update && apt-get install -y --no-install-recommends python3.10 python3-pip
+          wheelfile=$(find . -name 'cuda_quantum*cp310*x86_64.whl')
+          python3.10 -m pip install $wheelfile
+
+      - name: Get code
+        uses: actions/checkout@v4
+
+      - name: Test NVCF 
+        run: |
+          echo "### Submit to NVCF from Python wheels" >> $GITHUB_STEP_SUMMARY
+          export NVCF_API_KEY="${{ secrets.NVCF_API_KEY }}"
+          export NVCF_FUNCTION_ID="${{ secrets.NVCF_FUNCTION_ID }}"
+          export CUDAQ_LOG_LEVEL="info"
+          set +e # Allow script to keep going through errors
+          test_err_sum=0
+          for ex in `find examples/python -name '*.py'`; do 
+            filename=$(basename -- "$ex")
+            filename="${filename%.*}"
+            echo "Testing $filename:"
+            if [[ "$ex" == *"nvcf"* ]]; then
+              python3 $ex 1> /dev/null
+              test_status=$?
+              if [ $test_status -eq 0 ]; then
+                echo ":white_check_mark: Successfully ran test: $ex" >> $GITHUB_STEP_SUMMARY
+              else
+                echo ":x: Test failed (failed to execute): $ex" >> $GITHUB_STEP_SUMMARY
+                test_err_sum=$((test_err_sum+1))
+              fi
+            fi
+          done
+          set -e # Re-enable exit code error checking
+          if [ ! $test_err_sum -eq 0 ]; then
+            echo "::error::${test_err_sum} tests failed. See step summary for a list of failures"
+            exit 1
+          fi
+
   cleanup_nvcf_resources:
     name: Cleanup NVCF resources
     runs-on: ubuntu-latest
-    needs: [build_nvcf_image, deploy_nvcf_test_function, integration_test]
+    needs: [build_nvcf_image, deploy_nvcf_test_function, integration_test, wheel_integration_test]
     if: (success() || failure()) && (inputs.target == 'nvcf' || github.event_name == 'schedule' || inputs.target == 'nightly')
     environment: backend-validation
     steps:
