mpi check

diff --git a/.github/workflows/prebuilt_binaries.yml b/.github/workflows/prebuilt_binaries.yml
--- a/.github/workflows/prebuilt_binaries.yml
+++ b/.github/workflows/prebuilt_binaries.yml
@@ -307,19 +307,44 @@ jobs:
             --build-arg base_image=${{ matrix.os_image }} \
             --build-arg base_image_mpibuild=${{ inputs.platform_base_image }}
 
+      - name: Sanity checks
+        run: |
+          docker run --rm -dit --name cuda-quantum validation:local
+          (docker exec cuda-quantum bash -l validate.sh > /tmp/validation.out) && passed=true || passed=false
+          docker stop cuda-quantum
+
+          if ! $passed; then 
+            echo "::error::Validation failed; see job summary for more details."
+            exit 1
+          fi
+
       - name: MPI validation
         uses: ./.github/actions/run-in-docker
         with:
           image: validation:local
+          user: cudaq
           shell: bash -l
           run: |
             set +e # Allow script to keep going through errors
             sudo bash /install_sshclient.sh
+
+            if ${{ contains(matrix.os_image, 'redhat' ) }}; then
+              sudo dnf install -y --nobest --setopt=install_weak_deps=False gcc-toolset-11
+              source /opt/rh/gcc-toolset-11/enable
+              /usr/local/openmpi/bin/mpic++ mpi_cuda_check.cpp -o check.x && \
+              mpiexec -np 1 ./check.x
+              status=$?
+              if [ ! $status -eq 0 ]; then
+                echo "MPI check for CUDA awareness failed."
+                status_sum=$((status_sum+1))
+              fi
+            fi
+
             for ex in `find examples/other/distributed/ -name '*.cpp'`; do
               nvq++ -DCUDAQ_ENABLE_MPI_EXAMPLE=1 $ex
               status=$?
               if [ $status -eq 0 ]; then
-                mpiexec --allow-run-as-root -np 4 ./a.out
+                mpiexec -np 4 ./a.out
                 status=$?
                 filename=$(basename -- "$ex")
                 if [ $status -eq 0 ]; then
@@ -338,17 +363,6 @@ jobs:
               echo "::error::$status_sum examples failed; see the log for more detail."
               exit $status_sum
             fi
-
-      - name: Sanity checks
-        run: |
-          docker run --rm -dit --name cuda-quantum validation:local
-          (docker exec cuda-quantum bash -l validate.sh > /tmp/validation.out) && passed=true || passed=false
-          docker stop cuda-quantum
-
-          if ! $passed; then 
-            echo "::error::Validation failed; see job summary for more details."
-            exit 1
-          fi
 
       - name: Create job summary
         if: always() && !cancelled()
