debug assets download

diff --git a/.github/workflows/publishing.yml b/.github/workflows/publishing.yml
--- a/.github/workflows/publishing.yml
+++ b/.github/workflows/publishing.yml
@@ -190,8 +190,24 @@ jobs:
           name: wheel_assets
           path: /tmp/wheel_assets
           retention-days: 1
-          if-no-files-found: error      
-
+          if-no-files-found: error    
+      
+      # We can detele staging branch now 
+      - name: Clean up
+        run: |
+          # Clean up the staging branch that was used to trigger the GitLab pipeline.
+          git config --global user.name "cuda-quantum-bot"
+          git config --global user.email "cuda-quantum-bot@users.noreply.github.com"
+          function delete_staging_branch {
+            staging_branch=`echo "$2" | jq -r ".$1.staging_branch"`
+            echo "Delete staging branch $staging_branch ..."
+            # git push origin --delete $staging_branch || true
+          }
+          
+          for info_file in ${{ join(fromJson(steps.artifacts.outputs.python_wheels).info_files, ' ') }}; do
+            delete_staging_branch $info_file '${{ steps.artifacts.outputs.python_wheels }}'
+          done
+          
   cudaq_hpc:
     name: CUDA Quantum Docker image
     needs: assets
@@ -437,12 +453,13 @@ jobs:
         id: release_info
         run: |
           release_id=${{ fromJson(needs.assets.outputs.python_wheels)[format('{0}', matrix.info_file)].release_id }}
-          assets_folder=assets && mkdir "$assets_folder" && cd "$assets_folder"
+          assets_folder=assets && mkdir "$assets_folder" 
           build_info=${{ matrix.info_file }}*
           platform=`cat $build_info | grep -o 'platform: \S*' | cut -d ' ' -f 2`
           platform_id=`echo $platform | sed 's/linux\///g' | tr -d ' '`
           platform_arch=`([ "$platform_id" == "amd64" ] && echo x86_64) || ([ "$platform_id" == "arm64" ] && echo aarch64) || echo any`
           cudaqwheeldeps_image=`cat $build_info | grep -o 'cuda-quantum-wheeldeps-image: \S*' | cut -d ' ' -f 2`
+          ls -R tmp/wheel_assets
           cd tmp/wheel_assets/${{ matrix.info_file }}
           for file in `ls *zip`; do unzip "$file" -d "$assets_folder" && rm "$file"; done && cd -
           cd  "$assets_folder" && ls -R 
@@ -494,15 +511,6 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
 
-      - name: Clean up
-        # Only delete the branch once
-        if: matrix.python_version  == '3.10'  
-        run: |
-          # Clean up the staging branch that was used to trigger the GitLab pipeline.
-          staging_branch=${{ fromJson(needs.assets.outputs.python_wheels)[format('{0}', matrix.info_file)].staging_branch }}
-          git config --global user.name "cuda-quantum-bot"
-          git config --global user.email "cuda-quantum-bot@users.noreply.github.com"
-          git push origin --delete $staging_branch || ${{ inputs.assets_from_run != '' && true || false }}
 
   config:
     name: Configure validation
