update publishing pipeline to check side-by-side install of Python wheel

diff --git a/.github/workflows/publishing.yml b/.github/workflows/publishing.yml
--- a/.github/workflows/publishing.yml
+++ b/.github/workflows/publishing.yml
@@ -219,8 +219,7 @@ jobs:
             if [[ "$staging_branch" =~ ^bot\/.*$ ]]; then
               git push origin --delete $staging_branch
             else
-              echo "Unexpected staging branch."
-              exit 1
+              echo "::error::Unexpected staging branch." && exit 1
             fi
           }
           
@@ -788,7 +787,34 @@ jobs:
           relevant_line=`grep -n "Testing backends:" /tmp/validation.out | cut -d : -f1`
           tested_backends=`cat /tmp/validation.out | tail -n +$relevant_line | sed -e '/^$/,$d'`
           if [ -z "$(echo $tested_backends | grep nvidia-mgpu)" ]; then 
-            echo "Missing tests for nvidia-mgpu backend." && exit 1
+            echo "::error::Missing tests for nvidia-mgpu backend." && exit 1
+          fi
+
+      - name: Side-by-side installation of Python wheels
+        shell: bash
+        env:
+          BASH_ENV: ~/.bashrc
+        run: |
+          PYTHON="python3.$(ls /tmp/install/cuda_quantum*.whl | grep -o cp3[0-9]* | cut -c 4- | head -1)"
+          if [ -x "$(command -v apt-get)" ]; then
+            sudo apt-get update && sudo apt-get install -y --no-install-recommends $PYTHON $PYTHON-venv
+            $PYTHON -m venv "$HOME/.venv" && PATH="$HOME/.venv/bin:$PATH"
+          elif [ -x "$(command -v dnf)" ]; then
+            sudo dnf install -y --nobest --setopt=install_weak_deps=False $(echo $PYTHON | tr -d .)
+            $PYTHON -m ensurepip --upgrade
+          elif [ -x "$(command -v zypper)" ]; then
+            sudo zypper --non-interactive up --no-recommends
+            sudo zypper --non-interactive in --no-recommends $(echo $PYTHON | tr -d .)
+            $PYTHON -m ensurepip --upgrade            
+          fi
+
+          ${PYTHON} -m pip install /tmp/install/cuda_quantum*.whl
+          ${PYTHON} -m pip install pytest numpy
+          ${PYTHON} -m pytest -v /home/cudaq/python \
+            --ignore /home/cudaq/python/backends \
+            --ignore /home/cudaq/python/domains
+          if [ ! $? -eq 0 ]; then
+            echo "::error::Sanity tests failed for side-by-side Python support." && exit 1
           fi
 
   wheel_validation:
@@ -832,8 +858,7 @@ jobs:
           source validate_wheel.sh -w /tmp/install/cuda_quantum-*.whl -f /tmp -p 3.10
           set -e # Re-enable exit code error checking
           if [ "$status_sum" -ne "0" ]; then
-            echo "Error running validation script"
-            exit $status_sum
+            echo "::error::Error running validation script" && exit $status_sum
           fi
   
   wheel_validation_x86_simple:
@@ -883,8 +908,7 @@ jobs:
           done
           set -e # Re-enable exit code error checking
           if [ "$status_sum" -ne "0" ]; then
-            echo "Error running validation script"
-            exit $status_sum
+            echo "::error::Error running validation script" && exit $status_sum
           fi
   
   image_validation:
@@ -939,7 +963,7 @@ jobs:
           relevant_line=`grep -n "Testing backends:" /tmp/validation.out | cut -d : -f1`
           tested_backends=`cat /tmp/validation.out | tail -n +$relevant_line | sed -e '/^$/,$d'`
           if [ -z "$(echo $tested_backends | grep nvidia-mgpu)" ]; then 
-            echo "Missing tests for nvidia-mgpu backend." && exit 1
+            echo "::error::Missing tests for nvidia-mgpu backend." && exit 1
           fi
 
       - name: MPI validation 
