using validation script during publishing

diff --git a/.github/workflows/publishing.yml b/.github/workflows/publishing.yml
--- a/.github/workflows/publishing.yml
+++ b/.github/workflows/publishing.yml
@@ -762,22 +762,28 @@ jobs:
           chmod +x /tmp/install/install_cuda_quantum.*
           /tmp/install/install_cuda_quantum.* --accept
           rm -rf examples && mv docs/sphinx/examples examples && rm -rf examples/python
-          bash -l scripts/validate_container.sh default nvidia nvidia-mgpu tensornet tensornet-mps | tee /tmp/validation.out
 
-      - name: Create summary
-        if: always() && !cancelled()
-        run: |
-          if [ -f /tmp/validation.out ]; then
-            echo "## Validation" >> $GITHUB_STEP_SUMMARY
-            echo "The validation of the CUDA Quantum installation produced the following output:" >> $GITHUB_STEP_SUMMARY
-            echo '```text' >> $GITHUB_STEP_SUMMARY
-            cat /tmp/validation.out >> $GITHUB_STEP_SUMMARY
-            echo '```' >> $GITHUB_STEP_SUMMARY
+          install_path=`bash -lc "echo $CUDA_QUANTUM_PATH"`
+          backends_to_test=`\
+            for file in $(ls $install_path/targets/*.config); do \
+              if [ -n "$(cat $file | grep "GPU_REQUIREMENTS")" ]; then \
+                basename $file | cut -d "." -f 1; \
+              fi; \
+            done`
+
+          GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY \
+          bash -l scripts/validate_container.sh $backends_to_test | tee /tmp/validation.out
+
+          # Check that the tests included the nvidia-mgpu backend:
+          relevant_line=`grep -n "Testing backends:" /tmp/validation.out | cut -d : -f1`
+          tested_backends=`cat /tmp/validation.out | tail -n +$relevant_line | sed -e '/^$/,$d'`
+          if [ -z "$(echo $tested_backends | grep nvidia-mgpu)" ]; then 
+            echo "Missing tests for nvidia-mgpu backend." && exit 1
           fi
 
   image_validation:
     name: Docker image validation
-    needs: config
+    needs: [assets, config]
     runs-on: linux-amd64-gpu-v100-latest-1
     permissions:
       contents: read
@@ -796,45 +802,29 @@ jobs:
         TERM: xterm
 
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ needs.assets.outputs.github_commit }}
+
       - name: Basic validation (GPU backends)
         shell: bash
         run: |
-          status_sum=0 && set +e # Allow script to keep going through errors
-          # Skip some tests (multi-controlled gates) for the MPS backend (https://github.com/NVIDIA/cuda-quantum/issues/884)
-          mps_skipped_tests=(/home/cudaq/examples/cpp/algorithms/grover.cpp /home/cudaq/examples/cpp/basics/multi_controlled_operations.cpp /home/cudaq/examples/cpp/other/builder/builder.cpp /home/cudaq/examples/cpp/algorithms/amplitude_estimation.cpp)
-          for file in `ls $CUDA_QUANTUM_PATH/targets/*.config`; do
-            if [ -n "$(cat $file | grep "GPU_REQUIREMENTS")" ]; then
-              target=`basename $file | cut -d "." -f 1`
-              echo "## Execute on $target target" >> $GITHUB_STEP_SUMMARY
-              for ex in `find /home/cudaq/examples -name '*.cpp' -not -path '*/providers/*'`; do
-                if [[ " ${mps_skipped_tests[*]} " =~ " ${ex} " ]] && [[ "$target" = "tensornet-mps" ]] ; then
-                  echo ":white_flag: Issue: https://github.com/NVIDIA/cuda-quantum/issues/884. Test skipped." >> $GITHUB_STEP_SUMMARY
-                else
-                  filename=$(basename -- "$ex")
-                  nvq++ $ex --target $target
-                  status=$?
-                  if [ $status -eq 0 ]; then
-                    ./a.out
-                    status=$?
-                    if [ $status -eq 0 ]; then
-                      echo ":white_check_mark: Successfully ran $filename." >> $GITHUB_STEP_SUMMARY
-                    else
-                      echo ":x: Failed to execute $filename." >> $GITHUB_STEP_SUMMARY
-                      status_sum=$((status_sum+1))
-                    fi
-                  else
-                    echo ":x: Compilation failed for $filename." >> $GITHUB_STEP_SUMMARY
-                    status_sum=$((status_sum+1))
-                  fi
-                fi
-              done
-            fi
-          done
+          backends_to_test=`\
+              for file in $(ls $CUDA_QUANTUM_PATH/targets/*.config); \
+              do
+                  if [ -n "$(cat $file | grep "GPU_REQUIREMENTS")" ]; then \
+                    basename $file | cut -d "." -f 1; \
+                  fi; \
+              done`
+          GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY \
+          bash scripts/validate_container.sh $backends_to_test | tee /tmp/validation.out
 
-          set -e # Re-enable exit code error checking
-          if [ ! $status_sum -eq 0 ]; then
-            echo "::error::$status_sum examples failed; see step summary for a list of failures."
-            exit $status_sum
+          # Check that the tests included the nvidia-mgpu backend:
+          relevant_line=`grep -n "Testing backends:" /tmp/validation.out | cut -d : -f1`
+          tested_backends=`cat /tmp/validation.out | tail -n +$relevant_line | sed -e '/^$/,$d'`
+          if [ -z "$(echo $tested_backends | grep nvidia-mgpu)" ]; then 
+            echo "Missing tests for nvidia-mgpu backend." && exit 1
           fi
 
       - name: MPI validation 
