Update publishing.yml

diff --git a/.github/workflows/publishing.yml b/.github/workflows/publishing.yml
--- a/.github/workflows/publishing.yml
+++ b/.github/workflows/publishing.yml
@@ -272,26 +272,30 @@ jobs:
       - name: Install Cosign
         uses: sigstore/cosign-installer@v3.1.1
 
-      - name: Sign image
+      - name: Sign image with GitHub OIDC Token
+        if: steps.release_info.outputs.ngc_registry == ''
         env:
           DIGEST: ${{ steps.cudaq_build.outputs.digest }}
+          TAGS: ${{ steps.metadata.outputs.tags }}
+        run: |
+          cosign sign --yes --recursive "${TAGS}@${DIGEST}"
+
+      - name: Sign image with NGC CLI
+        if: steps.release_info.outputs.ngc_registry
+        env:
           TAGS: ${{ steps.metadata.outputs.tags }}
           NGC_CLI_API_KEY: ${{ secrets.NGC_CREDENTIALS }}
           NGC_CLI_ORG: ${{ github.repository_owner }}
           NGC_CLI_TEAM: 'nightly'
         run: |
-          if ${{ steps.release_info.outputs.ngc_registry != '' }}; then
-            wget -O ngccli_linux.zip --content-disposition \
-              https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/3.28.0/files/ngccli_linux.zip
-            if [ -z "$(sha256sum ngccli_linux.zip | grep -o '74f469a2082e90a4561f09eb0d483b67044e91be727066122253436c140a7b54 ')" ]; then
-              echo "::error::NGC CLI was corrupted during download." && exit 1
-            fi
-            unzip ngccli_linux.zip && chmod u+x ngc-cli/ngc
-            echo "Signing ${TAGS}"
-            ngc-cli/ngc registry image publish --source ${TAGS} ${TAGS} --sign
-          else
-            cosign sign --yes --recursive "${TAGS}@${DIGEST}"
+          wget -O ngccli_linux.zip --content-disposition \
+            https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/3.28.0/files/ngccli_linux.zip
+          if [ -z "$(sha256sum ngccli_linux.zip | grep -o '74f469a2082e90a4561f09eb0d483b67044e91be727066122253436c140a7b54 ')" ]; then
+            echo "::error::NGC CLI was corrupted during download." && exit 1
           fi
+          unzip ngccli_linux.zip && chmod u+x ngc-cli/ngc
+          echo "Signing ${TAGS}"
+          ngc-cli/ngc registry image publish --source ${TAGS} ${TAGS} --sign
 
       - name: Log in to the container registry
         if: vars.registry
