Enhance error detection in publishing script

diff --git a/.github/workflows/publishing.yml b/.github/workflows/publishing.yml
--- a/.github/workflows/publishing.yml
+++ b/.github/workflows/publishing.yml
@@ -828,7 +828,13 @@ jobs:
           ln -s $GITHUB_WORKSPACE/python/tests /tmp/tests
           ln -s $GITHUB_WORKSPACE/python/README.md .
           # Run the script w/ -q to run a shortened test
+          set +e # Allow script to keep going through errors (needed for skipped tests)
           source validate_wheel.sh -q -w /tmp/install/cuda_quantum-*.whl -f /tmp -p 3.10
+          set -e # Re-enable exit code error checking
+          if [ "$status_sum" -ne "0" ]; then
+            echo "Error running validation script"
+            exit $status_sum
+          fi
   
   image_validation:
     name: Docker image validation
