metapackage validation with conda instead of pip only
Signed-off-by: Bettina Heim <heimb@outlook.com>

diff --git a/.github/workflows/publishing.yml b/.github/workflows/publishing.yml
--- a/.github/workflows/publishing.yml
+++ b/.github/workflows/publishing.yml
@@ -930,71 +930,8 @@ jobs:
             exit 1
           fi
 
-  wheel_validation_conda:
-    name: Wheel validation, conda
-    if: false
-    needs: [assets, cudaq_wheels]
-    runs-on: linux-amd64-gpu-v100-latest-1
-    permissions:
-      contents: read
-
-    strategy:
-      matrix:
-        cuda_major: ['11', '12']
-      fail-fast: false
-
-    container:
-      image: ubuntu:22.04
-      options: --user root
-      env:
-        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
-        TERM: xterm
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.github_commit || needs.assets.outputs.github_commit }}
-
-      - name: Load wheel
-        uses: actions/download-artifact@v4
-        with:
-          name: x86_64-cu${{ matrix.cuda_major }}-py3.10-wheels
-          path: /tmp/install
-      
-      - name: Run validation
-        shell: bash
-        run: |
-          apt-get update && apt-get install -y --no-install-recommends \
-            ca-certificates vim wget unzip openssh-client
-          
-          # Extract README from wheel
-          cudaq_wheel=/tmp/install/cuda_quantum_cu${{ matrix.cuda_major }}*.whl 
-          wheelname=${cudaq_wheel##*/} && archive_name=${wheelname%.*}.zip
-          cp $cudaq_wheel /tmp/$wheelname && mv /tmp/$wheelname /tmp/$archive_name 
-          unzip /tmp/$archive_name -d /tmp/cudaq_wheel && rm -rf /tmp/$archive_name
-          metadata=/tmp/cudaq_wheel/*.dist-info/METADATA
-
-          # Setup links for validate_wheel.sh script
-          ln -s $GITHUB_WORKSPACE/scripts/validate_wheel.sh .
-          ln -s $GITHUB_WORKSPACE/docs/sphinx/examples/python /tmp/examples
-          ln -s $GITHUB_WORKSPACE/docs/sphinx/applications/python /tmp/applications
-          ln -s $GITHUB_WORKSPACE/docs/sphinx/targets/python /tmp/targets
-          ln -s $GITHUB_WORKSPACE/docs/sphinx/snippets/python /tmp/snippets
-          ln -s $GITHUB_WORKSPACE/python/tests /tmp/tests
-          ln -s $metadata /tmp/README.md
-
-          # Run the script w/ -q to run a shortened test
-          set +e # Allow script to keep going through errors (needed for skipped tests)
-          source validate_wheel.sh -w $cudaq_wheel -f /tmp -p 3.10
-          set -e # Re-enable exit code error checking
-          if [ "$status_sum" -ne "0" ]; then
-            echo "::error::Error running validation script" 
-            exit $status_sum
-          fi
-
-  metapackage_validation_piponly:
-    name: Python metapackage validation, pip only
+  wheel_validation_piponly:
+    name: Wheel validation, pip only
     needs: [assets, cudaq_wheels, cudaq_metapackages]
     runs-on: linux-amd64-gpu-v100-latest-1
     permissions:
@@ -1002,7 +939,7 @@ jobs:
 
     strategy:
       matrix:
-        cuda_major: ['11', '12']
+        cuda_major: ['', '11', '12']
       fail-fast: false
 
     container:
@@ -1026,6 +963,7 @@ jobs:
           merge-multiple: true
 
       - name: Load metapackage
+        if: ${{ matrix.cuda_major == '' }}
         uses: actions/download-artifact@v4
         with:
           name: ${{ needs.cudaq_metapackages.outputs.artifact_name }}
@@ -1043,12 +981,18 @@ jobs:
           python3 -m pip install pypiserver
           server=`find / -name pypi-server -executable -type f`
           $server run -p 8080 /tmp/packages & 
-
-          pip install --upgrade pip
-          pip install cudaq --extra-index-url http://localhost:8080 
-          if [ -z "$(pip list | grep cuda-quantum-cu${{ matrix.cuda_major }})" ]; then 
-            echo "::error::Missing installation of cuda-quantum-cu${{ matrix.cuda_major }} package."
-            exit 1
+          
+          if [ -n "${{ matrix.cuda_major }}" ]; then
+            pip install cuda-quantum-cu${{ matrix.cuda_major }} -v \
+              --extra-index-url http://localhost:8080 
+          else
+            pip install cudaq -v \
+              --extra-index-url http://localhost:8080 \
+            | tee /tmp/install.out
+            if [ -z "$(cat /tmp/install.out | grep -o 'Autodetection succeeded')" ]; then 
+              echo "::error::Autodetection to determine cudaq binary distribution failed."
+              exit 1
+            fi
           fi
 
           status_sum=0
@@ -1064,6 +1008,87 @@ jobs:
               fi
           done
           set -e # Re-enable exit code error checking
+          if [ "$status_sum" -ne "0" ]; then
+            echo "::error::Error running validation script" 
+            exit $status_sum
+          fi
+
+  metapackage_validation_conda:
+    name: Python metapackage validation, conda environment
+    if: false
+    needs: [assets, cudaq_wheels, cudaq_metapackages]
+    runs-on: linux-amd64-gpu-v100-latest-1
+    permissions:
+      contents: read
+
+    strategy:
+      matrix:
+        cuda_version: ['11.8', '12.6']
+      fail-fast: false
+
+    container:
+      image: ubuntu:22.04
+      options: --user root
+      env:
+        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
+        TERM: xterm
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ inputs.github_commit || needs.assets.outputs.github_commit }}
+
+      - name: Load wheels
+        uses: actions/download-artifact@v4
+        with:
+          name: x86_64-cu${{ matrix.cuda_major }}-py3.10-wheels
+          path: /tmp/wheels
+
+      - name: Load metapackage
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ needs.cudaq_metapackages.outputs.artifact_name }}
+          path: /tmp/packages
+
+      - name: Run validation
+        shell: bash
+        run: |
+          apt-get update && apt-get install -y --no-install-recommends \
+            ca-certificates vim wget unzip openssh-client
+          mv /tmp/wheels/* /tmp/packages && rmdir /tmp/wheels
+
+          python3 -m pip install pypiserver
+          server=`find / -name pypi-server -executable -type f`
+          $server run -p 8080 /tmp/packages & 
+
+          # Extract README from metapackage
+          cudaq_metapackage=cudaq-${{ needs.assets.outputs.cudaq_version }}
+          tar xf /tmp/packages/${cudaq_metapackage}.tar.gz && mv ${cudaq_metapackage}/README.md .
+          rm -rf ${cudaq_metapackage} && readme=README.md
+
+          # Setup links for validate_wheel.sh script
+          ln -s $GITHUB_WORKSPACE/scripts/validate_wheel.sh .
+          ln -s $GITHUB_WORKSPACE/docs/sphinx/examples/python /tmp/examples
+          ln -s $GITHUB_WORKSPACE/docs/sphinx/applications/python /tmp/applications
+          ln -s $GITHUB_WORKSPACE/docs/sphinx/targets/python /tmp/targets
+          ln -s $GITHUB_WORKSPACE/docs/sphinx/snippets/python /tmp/snippets
+          ln -s $GITHUB_WORKSPACE/python/tests /tmp/tests
+          ln -s $readme /tmp/README.md
+
+          # Run the script w/ -q to run a shortened test
+          set +e # Allow script to keep going through errors (needed for skipped tests)
+          source validate_wheel.sh \
+            -v ${{ needs.assets.outputs.cudaq_version }} \
+            -u http://localhost:8080 -f /tmp \
+            -c ${{ matrix.cuda_version }} -p 3.10
+          set -e # Re-enable exit code error checking
+
+          expected_dependency=cuda-quantum-cu$(echo ${{ matrix.cuda_version }} | cut -d . -f1)
+          if [ -z "$(python3 -m pip list | grep ${expected_dependency})" ]; then 
+            echo "::error::Missing installation of ${expected_dependency} package."
+            exit 1
+          fi
           if [ "$status_sum" -ne "0" ]; then
             echo "::error::Error running validation script" 
             exit $status_sum
@@ -1139,7 +1164,7 @@ jobs:
 
   clean_up:
     name: Clean up
-    needs: [assets, cudaq_images, cudaq_installers, cudaq_wheels, cudaq_metapackages, image_validation, installer_validation, wheel_validation_conda, metapackage_validation_piponly, create_release]
+    needs: [assets, cudaq_images, cudaq_installers, cudaq_wheels, cudaq_metapackages, image_validation, installer_validation, metapackage_validation_conda, wheel_validation_piponly, create_release]
     # Force this job to run even when some of the dependencies above are skipped.
     if: always() && !cancelled() && needs.assets.result != 'skipped' && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
     runs-on: ubuntu-latest
