Uncomment the wheel part of publishing.yml

diff --git a/.github/workflows/publishing.yml b/.github/workflows/publishing.yml
--- a/.github/workflows/publishing.yml
+++ b/.github/workflows/publishing.yml
@@ -275,7 +275,7 @@ jobs:
           tags: ${{ steps.metadata.outputs.tags }}
           labels: ${{ steps.metadata.outputs.labels }}
           platforms: ${{ steps.release_info.outputs.platforms }}
-          push: true
+          # push: true
 
   #     - name: Install Cosign
   #       uses: sigstore/cosign-installer@v3.1.1
@@ -358,177 +358,177 @@ jobs:
           git config --global user.email "cuda-quantum-bot@users.noreply.github.com"
           git push origin --delete $staging_branch || ${{ inputs.assets_from_run != '' && true || false }}
 
-  # cudaq_wheels:
-  #   name: CUDA Quantum Python wheels
-  #   needs: assets
-  #   runs-on: ubuntu-latest
+  cudaq_wheels:
+    name: CUDA Quantum Python wheels
+    needs: assets
+    runs-on: ubuntu-latest
 
-  #   environment:
-  #     name: ghcr-deployment
-  #     url: ${{ vars.deployment_url }}
+    environment:
+      name: ghcr-deployment
+      url: ${{ vars.deployment_url }}
 
-  #   strategy:
-  #     matrix:
-  #       info_file: ${{ fromJson(needs.assets.outputs.python_wheels).info_files }}
-  #       python_version: ['3.8', '3.9', '3.10', '3.11']
-  #     fail-fast: false
+    strategy:
+      matrix:
+        info_file: ${{ fromJson(needs.assets.outputs.python_wheels).info_files }}
+        python_version: ['3.8', '3.9', '3.10', '3.11']
+      fail-fast: false
 
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
-  #       with:
-  #         ref: ${{ needs.assets.outputs.github_commit }}
-  #         token: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ needs.assets.outputs.github_commit }}
+          token: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
 
-  #     - name: Retrieve assets
-  #       id: release_info
-  #       run: |
-  #         release_id=${{ fromJson(needs.assets.outputs.python_wheels)[format('{0}', matrix.info_file)].release_id }}
-  #         assets_folder=assets && mkdir "$assets_folder" && cd "$assets_folder"
-  #         while [ -z `ls | egrep '${{ matrix.info_file }}'` ]; do
-  #           (gh release download $release_id -R ${{ github.repository }}) || true
-  #           sleep 30 # waiting for assets to be created...
-  #         done
+      - name: Retrieve assets
+        id: release_info
+        run: |
+          release_id=${{ fromJson(needs.assets.outputs.python_wheels)[format('{0}', matrix.info_file)].release_id }}
+          assets_folder=assets && mkdir "$assets_folder" && cd "$assets_folder"
+          while [ -z `ls | egrep '${{ matrix.info_file }}'` ]; do
+            (gh release download $release_id -R ${{ github.repository }}) || true
+            sleep 30 # waiting for assets to be created...
+          done
 
-  #         build_info=${{ matrix.info_file }}*
-  #         platform=`cat $build_info | grep -o 'platform: \S*' | cut -d ' ' -f 2`
-  #         platform_id=`echo $platform | sed 's/linux\///g' | tr -d ' '`
-  #         platform_arch=`([ "$platform_id" == "amd64" ] && echo x86_64) || ([ "$platform_id" == "arm64" ] && echo aarch64) || echo any`
-  #         cudaqwheeldeps_image=`cat $build_info | grep -o 'cuda-quantum-wheeldeps-image: \S*' | cut -d ' ' -f 2`
-  #         for file in `ls *zip`; do unzip "$file" && rm "$file"; done && cd -
+          build_info=${{ matrix.info_file }}*
+          platform=`cat $build_info | grep -o 'platform: \S*' | cut -d ' ' -f 2`
+          platform_id=`echo $platform | sed 's/linux\///g' | tr -d ' '`
+          platform_arch=`([ "$platform_id" == "amd64" ] && echo x86_64) || ([ "$platform_id" == "arm64" ] && echo aarch64) || echo any`
+          cudaqwheeldeps_image=`cat $build_info | grep -o 'cuda-quantum-wheeldeps-image: \S*' | cut -d ' ' -f 2`
+          for file in `ls *zip`; do unzip "$file" && rm "$file"; done && cd -
 
-  #         echo "platform=$platform"
-  #         echo "platform_id=$platform_id"
-  #         echo "platform_arch=$platform_arch"
+          echo "platform=$platform"
+          echo "platform_id=$platform_id"
+          echo "platform_arch=$platform_arch"
   
-  #         echo "release_id=$release_id" >> $GITHUB_OUTPUT
-  #         echo "platform=$platform" >> $GITHUB_OUTPUT
-  #         echo "platform_arch=$platform_arch" >> $GITHUB_OUTPUT
-  #         echo "cudaqwheeldeps_image=$cudaqwheeldeps_image" >> $GITHUB_OUTPUT
-  #         echo "assets_folder=$assets_folder" >> $GITHUB_OUTPUT
-  #         echo "docker_output=type=local,dest=/tmp/wheels" >> $GITHUB_OUTPUT
-  #       env:
-  #         GH_TOKEN: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
+          echo "release_id=$release_id" >> $GITHUB_OUTPUT
+          echo "platform=$platform" >> $GITHUB_OUTPUT
+          echo "platform_arch=$platform_arch" >> $GITHUB_OUTPUT
+          echo "cudaqwheeldeps_image=$cudaqwheeldeps_image" >> $GITHUB_OUTPUT
+          echo "assets_folder=$assets_folder" >> $GITHUB_OUTPUT
+          echo "docker_output=type=local,dest=/tmp/wheels" >> $GITHUB_OUTPUT
+        env:
+          GH_TOKEN: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
 
-  #     - name: Build cuda-quantum wheel
-  #       id: build_wheel
-  #       uses: docker/build-push-action@v4
-  #       with:
-  #         context: .
-  #         file: ./docker/build/cudaq.wheel.Dockerfile
-  #         build-args: |
-  #           base_image=${{ steps.release_info.outputs.cudaqwheeldeps_image }}  
-  #           release_version=${{steps.release_info.outputs.release_id  }}
-  #           assets=${{ steps.release_info.outputs.assets_folder }}
-  #           python_version=$python_version
-  #         outputs: ${{ steps.release_info.outputs.docker_output }}
+      - name: Build cuda-quantum wheel
+        id: build_wheel
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          file: ./docker/build/cudaq.wheel.Dockerfile
+          build-args: |
+            base_image=${{ steps.release_info.outputs.cudaqwheeldeps_image }}  
+            release_version=${{steps.release_info.outputs.release_id  }}
+            assets=${{ steps.release_info.outputs.assets_folder }}
+            python_version=$python_version
+          outputs: ${{ steps.release_info.outputs.docker_output }}
 
-  #     - name: Upload wheels
-  #       uses: actions/upload-artifact@v3
-  #       with:
-  #         name: ${{ steps.release_info.outputs.platform_arch }}-wheels
-  #         path: /tmp/wheels
-  #         retention-days: 1
-  #         if-no-files-found: error
+      - name: Upload wheels
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ steps.release_info.outputs.platform_arch }}-wheels
+          path: /tmp/wheels
+          retention-days: 1
+          if-no-files-found: error
 
-  #     - name: Update release information
-  #       run: |
-  #         release_id=${{ steps.release_info.outputs.release_id }}
-  #         gh release view $release_id --json body --jq .body > rel_notes.txt
-  #         header_length=`cat rel_notes.txt | grep -n "Release notes generated" | cut -d ':' -f 1`
-  #         head -n $(($header_length - 1)) rel_notes.txt > new_notes.txt
-  #         echo -e "\nImage to create ${{ steps.release_info.outputs.platforms }} wheels:\n" >> new_notes.txt
-  #         echo "- cuda-quantum-devdeps (development dependencies only): ${{ steps.release_info.outputs.cudaqwheeldeps_image }}" >> new_notes.txt
-  #         (echo && tail -n +$header_length rel_notes.txt) >> new_notes.txt
-  #         gh release edit $release_id -R ${{ github.repository }} --notes-file new_notes.txt
-  #       env:
-  #         GH_TOKEN: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
+      - name: Update release information
+        run: |
+          release_id=${{ steps.release_info.outputs.release_id }}
+          gh release view $release_id --json body --jq .body > rel_notes.txt
+          header_length=`cat rel_notes.txt | grep -n "Release notes generated" | cut -d ':' -f 1`
+          head -n $(($header_length - 1)) rel_notes.txt > new_notes.txt
+          echo -e "\nImage to create ${{ steps.release_info.outputs.platforms }} wheels:\n" >> new_notes.txt
+          echo "- cuda-quantum-devdeps (development dependencies only): ${{ steps.release_info.outputs.cudaqwheeldeps_image }}" >> new_notes.txt
+          (echo && tail -n +$header_length rel_notes.txt) >> new_notes.txt
+          gh release edit $release_id -R ${{ github.repository }} --notes-file new_notes.txt
+        env:
+          GH_TOKEN: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
 
-  #     - name: Clean up
-  #       run: |
-  #         # Clean up the staging branch that was used to trigger the GitLab pipeline.
-  #         staging_branch=${{ fromJson(needs.assets.outputs.python_wheels)[format('{0}', matrix.info_file)].staging_branch }}
-  #         git config --global user.name "cuda-quantum-bot"
-  #         git config --global user.email "cuda-quantum-bot@users.noreply.github.com"
-  #         git push origin --delete $staging_branch || ${{ inputs.assets_from_run != '' && true || false }}
+      - name: Clean up
+        run: |
+          # Clean up the staging branch that was used to trigger the GitLab pipeline.
+          staging_branch=${{ fromJson(needs.assets.outputs.python_wheels)[format('{0}', matrix.info_file)].staging_branch }}
+          git config --global user.name "cuda-quantum-bot"
+          git config --global user.email "cuda-quantum-bot@users.noreply.github.com"
+          git push origin --delete $staging_branch || ${{ inputs.assets_from_run != '' && true || false }}
 
-  # create_release:
-  #   name: CUDA Quantum Release
-  #   needs: [assets, cudaq_hpc, cudaq_wheels]
-  #   if: needs.assets.outputs.release_title
-  #   runs-on: ubuntu-latest
+  create_release:
+    name: CUDA Quantum Release
+    needs: [assets, cudaq_hpc, cudaq_wheels]
+    if: needs.assets.outputs.release_title
+    runs-on: ubuntu-latest
 
-  #   environment:
-  #     name: ghcr-deployment
-  #     url: ${{ vars.deployment_url }}
+    environment:
+      name: ghcr-deployment
+      url: ${{ vars.deployment_url }}
 
-  #   steps:
-  #     - name: Download cuda-quantum wheels
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         path: wheelhouse
+    steps:
+      - name: Download cuda-quantum wheels
+        uses: actions/download-artifact@v3
+        with:
+          path: wheelhouse
 
-  #     # The python wheels are uploaded as a release asset, but not pushed to anywhere else.
-  #     # Note that PyPI packages cannot be updated once pushed;
-  #     #  - We could upload wheels to test-pypi when creating a release.
-  #     #  - The push to pypi itself should be done manually.
-  #     # See also: 
-  #     # https://github.com/pypa/gh-action-pypi-publish
-  #     # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
-  #     - name: Create release
-  #       run: |
-  #         for dir in `ls wheelhouse/`; do 
-  #           mv "wheelhouse/$dir"/* wheelhouse/ && rmdir "wheelhouse/$dir"
-  #         done
-  #         zip -r wheelhouse.zip wheelhouse
+      # The python wheels are uploaded as a release asset, but not pushed to anywhere else.
+      # Note that PyPI packages cannot be updated once pushed;
+      #  - We could upload wheels to test-pypi when creating a release.
+      #  - The push to pypi itself should be done manually.
+      # See also: 
+      # https://github.com/pypa/gh-action-pypi-publish
+      # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
+      - name: Create release
+        run: |
+          for dir in `ls wheelhouse/`; do 
+            mv "wheelhouse/$dir"/* wheelhouse/ && rmdir "wheelhouse/$dir"
+          done
+          zip -r wheelhouse.zip wheelhouse
 
-  #         release_id=${{ inputs.assets_from_run || github.run_id }}
-  #         release_title="${{ needs.assets.outputs.release_title }}"
-  #         github_commit=${{ needs.assets.outputs.github_commit }}
-  #         version=${{ needs.assets.outputs.release_version }}
-  #         versions=`gh release list -R ${{ github.repository }} --exclude-drafts --exclude-pre-releases | egrep -o "([0-9]{1,}\.)+[0-9]{1,}\S*" | sort -r -V`
-  #         latest_tag=`echo $versions | cut -d ' ' -f 1`
-  #         prerelease=`([ "$(echo $version | egrep -o '([0-9]{1,}\.)+[0-9]{1,}')" == "$version" ] && echo '') || echo '--prerelease'`
+          release_id=${{ inputs.assets_from_run || github.run_id }}
+          release_title="${{ needs.assets.outputs.release_title }}"
+          github_commit=${{ needs.assets.outputs.github_commit }}
+          version=${{ needs.assets.outputs.release_version }}
+          versions=`gh release list -R ${{ github.repository }} --exclude-drafts --exclude-pre-releases | egrep -o "([0-9]{1,}\.)+[0-9]{1,}\S*" | sort -r -V`
+          latest_tag=`echo $versions | cut -d ' ' -f 1`
+          prerelease=`([ "$(echo $version | egrep -o '([0-9]{1,}\.)+[0-9]{1,}')" == "$version" ] && echo '') || echo '--prerelease'`
           
-  #         rel_notes="Release created by workflow [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})."
-  #         rel_notes+=$(echo "<br/>GitHub commit [$github_commit](https://github.com/${{ github.repository }}/tree/$github_commit)")
-  #         gh release create $release_id --title $release_id -R ${{ github.repository }} \
-  #           --target $github_commit --draft $prerelease \
-  #           --generate-notes --notes-start-tag $latest_tag --notes "$rel_notes"
-  #         gh release upload $release_id -R ${{ github.repository }} wheelhouse.zip --clobber
-  #         gh release edit $release_id -R ${{ github.repository }} \
-  #           --title "$release_title" --tag $version $prerelease # --draft=false
-  #       env:
-  #         GH_TOKEN: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
+          rel_notes="Release created by workflow [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})."
+          rel_notes+=$(echo "<br/>GitHub commit [$github_commit](https://github.com/${{ github.repository }}/tree/$github_commit)")
+          gh release create $release_id --title $release_id -R ${{ github.repository }} \
+            --target $github_commit --draft $prerelease \
+            --generate-notes --notes-start-tag $latest_tag --notes "$rel_notes"
+          gh release upload $release_id -R ${{ github.repository }} wheelhouse.zip --clobber
+          gh release edit $release_id -R ${{ github.repository }} \
+            --title "$release_title" --tag $version $prerelease # --draft=false
+        env:
+          GH_TOKEN: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
 
-  # clean_up:
-  #   name: Clean up
-  #   needs: [assets, cudaq_hpc, cudaq_wheels, create_release]
-  #   # Force this job to run even when some of the dependencies above are skipped.
-  #   if: always() && !cancelled() && needs.assets.result != 'skipped' && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
-  #   runs-on: ubuntu-latest
+  clean_up:
+    name: Clean up
+    needs: [assets, cudaq_hpc, cudaq_wheels, create_release]
+    # Force this job to run even when some of the dependencies above are skipped.
+    if: always() && !cancelled() && needs.assets.result != 'skipped' && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
+    runs-on: ubuntu-latest
 
-  #   environment:
-  #     name: ghcr-deployment
-  #     url: ${{ vars.deployment_url }}
+    environment:
+      name: ghcr-deployment
+      url: ${{ vars.deployment_url }}
 
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-  #     - name: Clean up
-  #       id: cleanup
-  #       run: |
-  #         # Delete the draft release(s) used to exchange data between GitLab and GitHub.
-  #         for release_id in `echo ${{ needs.assets.outputs.releases }}`; do
-  #           if [ -n "$(gh release list | grep -s $release_id)" ]; then
-  #             echo "## Draft Release $release_id:" >> $GITHUB_STEP_SUMMARY
-  #             gh release view $release_id --json body --jq .body > rel_notes.txt
-  #             header_length=`cat rel_notes.txt | grep -n "Release notes generated" | cut -d ':' -f 1`
-  #             head -n $(($header_length - 1)) rel_notes.txt >> $GITHUB_STEP_SUMMARY
-  #             gh release delete $release_id -R ${{ github.repository }} -y
-  #             echo "Deleted release $release_id."
-  #           fi
-  #         done
-  #       env:
-  #         GH_TOKEN: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
+      - name: Clean up
+        id: cleanup
+        run: |
+          # Delete the draft release(s) used to exchange data between GitLab and GitHub.
+          for release_id in `echo ${{ needs.assets.outputs.releases }}`; do
+            if [ -n "$(gh release list | grep -s $release_id)" ]; then
+              echo "## Draft Release $release_id:" >> $GITHUB_STEP_SUMMARY
+              gh release view $release_id --json body --jq .body > rel_notes.txt
+              header_length=`cat rel_notes.txt | grep -n "Release notes generated" | cut -d ':' -f 1`
+              head -n $(($header_length - 1)) rel_notes.txt >> $GITHUB_STEP_SUMMARY
+              gh release delete $release_id -R ${{ github.repository }} -y
+              echo "Deleted release $release_id."
+            fi
+          done
+        env:
+          GH_TOKEN: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
