Update publishing.yml

diff --git a/.github/workflows/publishing.yml b/.github/workflows/publishing.yml
--- a/.github/workflows/publishing.yml
+++ b/.github/workflows/publishing.yml
@@ -498,23 +498,43 @@ jobs:
 
     container:
       image: ${{ matrix.image_hash }}
-      options: --user root # otherwise checkout doesn't work
       env:
         NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ needs.assets.outputs.github_commit }}
-
-      # FIXME: better test cases and create a nicer summary...
-      - name: Basic validation
+      - name: Basic validation (GPU backends)
         run: |
-          echo "## Validation" >> $GITHUB_STEP_SUMMARY
-          echo '```text' >> $GITHUB_STEP_SUMMARY
-          bash validate_container.sh >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
+          set +e # Allow script to keep going through errors
+          for file in `ls $CUDA_QUANTUM_PATH/targets/*.config`; do
+            if [ -n "$(cat $file | grep "GPU_REQUIREMENTS")" ]; then
+              target=`basename $file | cut -d "." -f 1`
+              echo "## Execute on $target target" >> $GITHUB_STEP_SUMMARY
+              for ex in `find examples/cpp -name '*.cpp'`; do
+                filename=$(basename -- "$ex")
+                nvq++ $ex --target $target
+                status=$?
+                if [ $status -eq 0 ]; then
+                  ./a.out
+                  status=$?
+                  if [ $status -eq 0 ]; then
+                    echo ":white_check_mark: Successfully ran $filename." >> $GITHUB_STEP_SUMMARY
+                  else
+                    echo ":x: Failed to execute $filename." >> $GITHUB_STEP_SUMMARY
+                    status_sum=$((status_sum+1))
+                  fi
+                else
+                  echo ":x: Compilation failed for $filename." >> $GITHUB_STEP_SUMMARY
+                  status_sum=$((status_sum+1))
+                fi
+              done
+            fi
+          done
+
+          set -e # Re-enable exit code error checking
+          if [ ! $status_sum -eq 0 ]; then
+            echo "::error::$status_sum examples failed; see step summary for a list of failures."
+            exit $status_sum
+          fi
 
   create_release:
     name: CUDA Quantum Release
