publishing: use --target nvidia --target-option fp64
Signed-off-by: Mitchell <mitch_dz@hotmail.com>

diff --git a/.github/workflows/publishing.yml b/.github/workflows/publishing.yml
--- a/.github/workflows/publishing.yml
+++ b/.github/workflows/publishing.yml
@@ -1091,11 +1091,13 @@ jobs:
           set +e # Allow script to keep going through errors
           # Verify that the necessary GPU targets are installed and usable
           # Note nvidia-mgpu requires MPI, so it is not available with this method.
-          for tgt in nvidia nvidia-fp64 tensornet; do
-              echo "Running with target ${tgt}"
-              python3 docs/sphinx/examples/python/intro.py --target ${tgt}
+          # List of full target options
+          targets=("--target nvidia" "--target nvidia --target-option fp64" "--target tensornet")
+          for tgt in "${targets[@]}"; do
+              echo "Running with ${tgt}"
+              python3 docs/sphinx/examples/python/intro.py $tgt
               if [ $? -ne 0 ]; then 
-                  echo -e "\e[01;31mPython trivial test for target ${tgt} failed.\e[0m" >&2
+                  echo -e "\e[01;31mPython trivial test for ${tgt} failed.\e[0m" >&2
                   status_sum=$((status_sum+1))
               fi
           done
