Fix CI

diff --git a/.github/workflows/python_wheels.yml b/.github/workflows/python_wheels.yml
--- a/.github/workflows/python_wheels.yml
+++ b/.github/workflows/python_wheels.yml
@@ -215,19 +215,24 @@ jobs:
                 exit 1
               fi
             done
-            echo "$(uname -a)"
-            if [  -n "$(uname -a | grep Ubuntu)" ]; then
-              # Install mpi4py when validating the wheel on Ubuntu
-              # to run the MPI plugin test.
-              apt-get update && apt-get install -y --no-install-recommends libopenmpi-dev
-              python${{ inputs.python_version }} -m pip install --user mpi4py
-              mpirun --allow-run-as-root -np 4 python${{ inputs.python_version }} -m pytest -v /tmp/tests/parallel/test_mpi_api.py
-              pytest_mpi_status=$?
-              if [ ! $pytest_mpi_status -eq 0 ]; then
-                echo "::error file=python_wheel.yml::Python MPI plugin test failed with status $pytest_mpi_status."
-                exit 1
-              fi
-            fi 
+
+      - name: Run Python MPI tests
+        if: ${{ matrix.os_image }} == 'ubuntu:22.04'
+        uses: ./.github/actions/run-in-docker
+        with:
+          image: wheel_validation:local
+          shell: bash
+          run: |
+            # Install mpi4py when validating the wheel on Ubuntu
+            # to run the MPI plugin test.
+            apt-get update && apt-get install -y --no-install-recommends libopenmpi-dev
+            python${{ inputs.python_version }} -m pip install --user mpi4py
+            mpirun --allow-run-as-root -np 4 python${{ inputs.python_version }} -m pytest -v /tmp/tests/parallel/test_mpi_api.py
+            pytest_mpi_status=$?
+            if [ ! $pytest_mpi_status -eq 0 ]; then
+              echo "::error file=python_wheel.yml::Python MPI plugin test failed with status $pytest_mpi_status."
+              exit 1
+            fi
 
       - name: Validate Python examples
         run: |
