* Updated tests to match the qubit reordering work. * Added the 'remote' tests to Python wheels CI check.

diff --git a/.github/workflows/python_wheels.yml b/.github/workflows/python_wheels.yml
--- a/.github/workflows/python_wheels.yml
+++ b/.github/workflows/python_wheels.yml
@@ -232,13 +232,6 @@ jobs:
               exit 1
             fi
 
-            python${{ inputs.python_version }} -m pytest -v /tmp/tests/compiler
-            pytest_status=$?
-            if [ ! $pytest_status -eq 0 ]; then
-              echo "::error file=python_wheel.yml::Python 'compiler' tests failed with status $pytest_status."
-              exit 1
-            fi
-
             python${{ inputs.python_version }} -m pytest -v /tmp/tests/domains
             pytest_status=$?
             if [ ! $pytest_status -eq 0 ]; then
@@ -265,6 +258,13 @@ jobs:
             pytest_status=$?
             if [ ! $pytest_status -eq 0 ]; then
               echo "::error file=python_wheel.yml::Python 'parallel' tests failed with status $pytest_status."
+              exit 1
+            fi
+
+            python${{ inputs.python_version }} -m pytest -v /tmp/tests/remote
+            pytest_status=$?
+            if [ ! $pytest_status -eq 0 ]; then
+              echo "::error file=python_wheel.yml::Python 'remote' tests failed with status $pytest_status."
               exit 1
             fi
 
