* Workaround for remote multi QPU implementation * Enabling 'remote' backend tests * Applied code formatting
Co-authored-by: Thien Nguyen <thiennguyen@nvidia.com>

diff --git a/.github/workflows/python_wheels.yml b/.github/workflows/python_wheels.yml
--- a/.github/workflows/python_wheels.yml
+++ b/.github/workflows/python_wheels.yml
@@ -260,13 +260,12 @@ jobs:
               exit 1
             fi
 
-            ## [SKIP_TEST]: Reason - "RuntimeError: Unable to retrieve RemoteSimulatorQPU implementation"
-            # python${{ inputs.python_version }} -m pytest -v /tmp/tests/remote
-            # pytest_status=$?
-            # if [ ! $pytest_status -eq 0 ]; then
-            #   echo "::error file=python_wheel.yml::Python 'remote' tests failed with status $pytest_status."
-            #   exit 1
-            # fi
+            python${{ inputs.python_version }} -m pytest -v /tmp/tests/remote
+            pytest_status=$?
+            if [ ! $pytest_status -eq 0 ]; then
+              echo "::error file=python_wheel.yml::Python 'remote' tests failed with status $pytest_status."
+              exit 1
+            fi
 
             python${{ inputs.python_version }} -m pytest -v /tmp/tests/unittests
             pytest_status=$?
