check if an existing image has the same layers for devdeps

diff --git a/.github/workflows/test_in_devenv.yml b/.github/workflows/test_in_devenv.yml
--- a/.github/workflows/test_in_devenv.yml
+++ b/.github/workflows/test_in_devenv.yml
@@ -5,6 +5,9 @@ on:
         type: string
         required: false
         default: linux/amd64
+      devdeps_image:
+        required: false
+        type: string
       devdeps_cache:
         required: true
         type: string
@@ -29,6 +32,8 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Restore environment
+        id: restore_devdeps
+        if: inputs.devdeps_image == ''
         uses: actions/cache/restore@v3
         with:
           path: ${{ inputs.devdeps_archive }}
@@ -47,17 +52,20 @@ jobs:
       - name: Build CUDA Quantum
         id: cudaq_build
         run: |
-          load_output=`docker load --input "${{ inputs.devdeps_archive }}"`
-          base_image=`echo "$load_output" | grep -o 'Loaded image: \S*:\S*' | head -1 | cut -d ' ' -f 3`
-          devdeps_tag=`echo $base_image | rev | cut -d ":" -f 1 | rev`
+          if ${{ steps.restore_devdeps.outcome != 'skipped' }}; then
+            load_output=`docker load --input "${{ inputs.devdeps_archive }}"`
+            base_image=`echo "$load_output" | grep -o 'Loaded image: \S*:\S*' | head -1 | cut -d ' ' -f 3`
+          elif ${{ inputs.devdeps_image != '' }}; then
+            base_image=${{ inputs.devdeps_image }}
+          else
+            echo "::error file=test_in_devenv.yml::Missing configuration for development dependencies. Either specify the image (i.e. provide devdeps_image) or cache (i.e. provide devdeps_cache and devdeps_archive) that should be used for the build."
+            exit 1
+          fi
 
           DOCKER_BUILDKIT=1 docker build --platform ${{ inputs.platform }} \
             -t cuda-quantum-dev:local -f docker/build/cudaq.dev.Dockerfile . \
             --build-arg base_image=$base_image \
             --build-arg install="CMAKE_BUILD_TYPE=Debug"
-          
-          tag_prefix=`echo $devdeps_tag | cut -d "_" -f 1`
-          echo "tag_prefix=$tag_prefix" >> $GITHUB_OUTPUT
 
       - name: Test CUDA Quantum
         uses: addnab/docker-run-action@v3
@@ -80,7 +88,8 @@ jobs:
         if: inputs.export_environment
         run: |
           output_directory=/tmp
-          filename=${{ steps.cudaq_build.outputs.tag_prefix }}_build
+          platform_id=`echo ${{ inputs.platform }} | sed 's/linux\///g' | tr -d ' '`
+          filename=${platform_id}_debug_build
 
           docker run --name cuda-quantum-dev cuda-quantum-dev:local
           docker export cuda-quantum-dev > $output_directory/$filename.tar
@@ -108,6 +117,8 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Restore environment
+        id: restore_devdeps
+        if: inputs.devdeps_image == ''
         uses: actions/cache/restore@v3
         with:
           path: ${{ inputs.devdeps_archive }}
@@ -126,16 +137,19 @@ jobs:
       - name: Set up dev environment
         id: dev_env
         run: |
-          load_output=`docker load --input "${{ inputs.devdeps_archive }}"`
-          base_image=`echo "$load_output" | grep -o 'Loaded image: \S*:\S*' | head -1 | cut -d ' ' -f 3`
-          devdeps_tag=`echo $base_image | rev | cut -d ":" -f 1 | rev`
+          if ${{ steps.restore_devdeps.outcome != 'skipped' }}; then
+            load_output=`docker load --input "${{ inputs.devdeps_archive }}"`
+            base_image=`echo "$load_output" | grep -o 'Loaded image: \S*:\S*' | head -1 | cut -d ' ' -f 3`
+          elif ${{ inputs.devdeps_image != '' }}; then
+            base_image=${{ inputs.devdeps_image }}
+          else
+            echo "::error file=test_in_devenv.yml::Missing configuration for development dependencies. Either specify the image (i.e. provide devdeps_image) or cache (i.e. provide devdeps_cache and devdeps_archive) that should be used for the build."
+            exit 1
+          fi
 
           DOCKER_BUILDKIT=1 docker build --platform ${{ inputs.platform }} \
             -t dev_env:local -f docker/build/cudaq.dev.Dockerfile . \
             --build-arg base_image=$base_image 
-
-          tag_prefix=`echo $devdeps_tag | cut -d "_" -f 1`
-          echo "tag_prefix=py_$tag_prefix" >> $GITHUB_OUTPUT
 
       - name: Build and test CUDA Quantum (Python)
         uses: addnab/docker-run-action@v3
@@ -171,7 +185,8 @@ jobs:
         if: inputs.export_environment
         run: |
           output_directory=/tmp
-          filename=${{ steps.dev_env.outputs.tag_prefix }}_build
+          platform_id=`echo ${{ inputs.platform }} | sed 's/linux\///g' | tr -d ' '`
+          filename=${platform_id}_python_build
 
           docker run --name dev_env dev_env:local
           docker export dev_env > $output_directory/$filename.tar
