Improve handling of quantum library calls in kernel function bodies (#1171)
* Improve handling of quantum library calls in kernel body

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* add the extra ast test

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* spell / format

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* try and fix issues with CI finding the right python package, fix bug with same kernel name

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* fixes for build errors, put back the ctest target

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* Add python path to pycudaq tests

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* format

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* wip

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* Unify the ast/eager tests. Fixed bug with lambda being popped off the value stack to early

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* ci

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* rename test files, remove print stmt

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* Fix bug in py_alt_launch_kernel where MLIR Context was stored beyond its lifetime

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* address pr comments

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* pr feedback

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* Fix issue with observe_async with eager mode kernels

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

* Implement sample_async for eager mode

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

---------

Signed-off-by: Alex McCaskey <amccaskey@nvidia.com>

diff --git a/.github/workflows/test_in_devenv.yml b/.github/workflows/test_in_devenv.yml
--- a/.github/workflows/test_in_devenv.yml
+++ b/.github/workflows/test_in_devenv.yml
@@ -219,6 +219,13 @@ jobs:
               echo "::error file=test_in_devenv.yml::Python tests failed with status $pytest_status."
               exit 1
             fi
+            CUDAQ_PYTEST_EAGER_MODE=OFF python3 -m pytest -v python/tests/ \
+              --ignore python/tests/backends
+            pytest_status=$?
+            if [ ! $pytest_status -eq 0 ]; then
+              echo "::error file=test_in_devenv.yml::Python tests failed with status $pytest_status."
+              exit 1
+            fi
             for backendTest in python/tests/backends/*.py; do
               python3 -m pytest -v $backendTest
               pytest_status=$?
